### ISSUE TITLE
Particle Servo Library not Implemented

### ISSUE THREAD

**Issue by scottefein** [hybridgroup/gobot#160]
@zankich we talked about this last night, but yeah-doesn't appear to be any implementation of the SparkCore Servo Library since that support got added to Tinker.

**Comment by deadprogram** [comment]
Hi @scottefein I know this is seriously like years overdue, but just added support to the `dev` branch for this feature.

**Comment by scottefein** [comment]
Haha nice!! Thanks @deadprogram :)
