### ISSUE TITLE
Cant start gobot with raspberry pi adapter and servo driver

### ISSUE THREAD

**Issue by razic** [hybridgroup/gobot#166]
here is my code:

```go
package main

import (
        "github.com/hybridgroup/gobot"
        "github.com/hybridgroup/gobot/platforms/gpio"
        "github.com/hybridgroup/gobot/platforms/raspi"
        "log"
        "time"
)

func main() {
        gbot := gobot.NewGobot()
        r := raspi.NewRaspiAdaptor("raspi")
        servo := gpio.NewServoDriver(r, "servo", "23")
        work := func() {
                gobot.Every(10*time.Second, func() {
                        i := uint8(gobot.Rand(180))
                        log.Printf("Moving servo to %d", i)
                        servo.Move(i)
                })
        }
        robot := gobot.NewRobot(
                "servoBot",
                []gobot.Connection{r},
                []gobot.Device{servo},
                work,
        )

        gbot.AddRobot(robot)
        gbot.Start()
}
```

and this is the error is get

```bash
./main.go:14: cannot use r (type *raspi.RaspiAdaptor) as type gpio.Servo in argument to gpio.NewServoDriver:                                                                                                        │
        *raspi.RaspiAdaptor does not implement gpio.Servo (missing InitServo method)
```

any suggestions?

**Comment by razic** [comment]
@zankich great. sounds like we're almost there. is it possible you would be able to explain on a high level a bit more in-depth what it would take to get the pi blaster support going?

correct me if i'm wrong, but it seems like pi-blaster is either a process or a script that needs to be run at least once. then, we can write values to `/dev/pi-blaster`?

**Comment by zankich** [comment]
@razic I created a branch with initial pi-blaster support https://github.com/hybridgroup/gobot/tree/raspi_pwm. In order to get this to work you'll have to follow the installation instructions for [pi-blaster](https://github.com/sarfata/pi-blaster#how-to-build-and-install). I don't currently have access to a raspberry pi, so I only tested locally with manually verifying values and it should work.... If you're feeling brave you can check out that branch and let me know how it goes!

**Comment by SellJamHere** [comment]
Has there been any further work on PWM support?

**Comment by zankich** [comment]
@razic and @SellJamHere pwm support has just landed in the master branch. You need to follow the instructions [here](https://github.com/hybridgroup/gobot/tree/master/platforms/raspi#enabling-pwm-output-on-gpio-pins) to enable PWM pins.

**Comment by edgarsilva** [comment]
We should close this since pwm support has been added, or are we waiting for release?

**Comment by zankich** [comment]
This has been released and I tested with a servo and led on a raspi b+

**Comment by matipan** [comment]
@zankich Do you have an example I could follow? I'm trying with a MG90 servo tower connected to GPIO 11 on a pi b+ but it does not seem to be working

**Comment by deadprogram** [comment]
You might want to open a new issue @matipan this one has been closed for a long time.
