### ISSUE TITLE
Support for the TinkerForge platform

### ISSUE THREAD

**Issue by dominikschulz** [hybridgroup/gobot#167]
Hi,

it would be great if you would add support for the Tinkerforge (www.tinkerforge.com) platform in addition to the existing platforms. It's similar to the arduino platform but IMHO simpler and more approacheable to newbies.

**Comment by gen2thomas** [comment]
The [RED Brick](https://www.tinkerforge.com/de/doc/Hardware/Bricks/RED_Brick.html#red-brick) is discontinued. Another SoC can be the alternative (e.g. Raspi). [Other pricklets](https://www.tinkerforge.com/de/doc/Primer.html#primer-bricks) are ESP32 based, so I think a platform request should be done in the [TinyGo](https://github.com/tinygo-org/tinygo) project.

If there is any interest for implementing [HAT](https://www.tinkerforge.com/de/doc/Hardware/Bricks/HAT_Brick.html#hat-brick) support for Raspi or for a [Bricklet](https://www.tinkerforge.com/de/doc/Hardware/Bricklets/Bricklets.html), please file issues for the corresponding hardware.
