### ISSUE TITLE
Servos: setting minimum and maximum "pulse width" - Arduino

### ISSUE THREAD

**Issue by pipejesus** [hybridgroup/gobot#172]
Using the Arduino libraries i can set the maximum and minimum pulse width for my servo so that i can calibrate it. Is it possible with Gobot ? What i mean is this : http://arduino.cc/en/Reference/ServoAttach

**Comment by zankich** [comment]
@pipejesus at the moment no, we don't have that capability, however I'm currently working on a refactor of our firmata implementation and based off of the [servo](https://github.com/firmata/protocol/blob/master/servos.md) protocol document, it should be easy to add.

**Comment by pipejesus** [comment]
Superb! Great project, thank you Adrian for bringing Gobot to Earth :-)

**Comment by losinggeneration** [comment]
It looks like this might be implemented (at least on the client library.) https://github.com/hybridgroup/gobot/blob/dev/platforms/firmata/client/client.go#L217 However, it looks like the bytes are sent as max,min instead of min,max unless I'm misunderstanding the code and/or protocol doc.

**Comment by deadprogram** [comment]
Hi @losinggeneration looks to me like you are absolutely correct. Would you be willing to submit a PR with that fix?

**Comment by losinggeneration** [comment]
I'll pick up a servo tomorrow to verify it works and then get a PR in for it.

**Comment by deadprogram** [comment]
Seems like this was addressed already. Please reopen if needed.
