### ISSUE TITLE
Arduino LED example doesnt work with runtime error: index out of range

### ISSUE THREAD

**Issue by lkalneus** [hybridgroup/gobot#177]
Error screenshot: https://yadi.sk/i/3PPaJ05eeuQ9Z

OS: Win8 x64, Platform: Arduino UNO v3.0

**Comment by deadprogram** [comment]
Hi, @lkalneus did you flash the Firmata sketch onto your Arduino before running Gobot? You can use Gort (http://gort.io) to do this.

**Comment by lkalneus** [comment]
@deadprogram, yeah you are right.
It was a stupid mistake, sorry)
