### ISSUE TITLE
Is Orbotix Ollie supported ?

### ISSUE THREAD

**Issue by coxx** [hybridgroup/gobot#190]
Hello guys!
Can you explain is Ollie supported or just Sphero ?

**Comment by deadprogram** [comment]
Hi, @coxx 

We do not have Ollie support yet, due to still adding core Bluetooth LE support. The Sphero is Bluetooth classic, and so was easier to add support.

Hope that helps!

**Comment by ryanfaerman** [comment]
Any updates on Ollie/Bluetooth LE support?

**Comment by deadprogram** [comment]
Hi, @ryanfaerman I am working on BLE support, hope to have something pretty soon.

Then the Ollie/BB-8 API will be next!

**Comment by ryanfaerman** [comment]
Is there anything I can do to help?

I've recently purchased a BB8 sphero and I'm debating returning it and getting a Sprk so that I can play with things.

**Comment by deadprogram** [comment]
Checkout my work in progress branch here: https://github.com/hybridgroup/gobot/tree/feature/ble-wip

**Comment by deadprogram** [comment]
Hi, everyone

Initial support for Ollie & BB-8 is now in Gobot 0.12+ sorry I did not update this issue. Please check it out!
