### ISSUE TITLE
More Precise Definitions of Driver and Adaptor Interfaces

### ISSUE THREAD

**Issue by saulshanabrook** [hybridgroup/gobot#197]
As I said earlier, I am implementing a DMX USB Pro platform. I am using the `github.com/hybridgroup/gobot/platforms/sphero` package as an example, but went back to the defenitions of [`Driver`](https://github.com/hybridgroup/gobot/blob/e7beae51bdbbc4d3f6d742f631fa100b94b1335b/driver.go#L3-L13) and and the [`Adaptor`](https://github.com/hybridgroup/gobot/blob/e7beae51bdbbc4d3f6d742f631fa100b94b1335b/adaptor.go#L3-L11) interfaces to see exactly what methods need to be defined.

I had a couple of questions about how the methods should be implemented for each.
1. What should the behavior of `Adaptor.Connect()` be if it is called a second time, after it has already connected?
2. Should an adapter be able to be re-connected to after `Adaptor.Finalize()` has been called?
3. Should `Adaptor.Finalize()` return an error if it wasn't connected to before?
4. Same questions, but for the `Driver.Start()` and the `Driver.Halt()` methods.

**Comment by deadprogram** [comment]
The docs are now updated with more info. Thanks, everyone.
