### ISSUE TITLE
Build all example docs

### ISSUE THREAD

**Issue by saulshanabrook** [hybridgroup/gobot#201]
If possible, maybe it would be nice to build all example code, to verify that at least it still builds.

I am not sure if there are any tools that make this easier.

**Comment by zankich** [comment]
@saulshanabrook I actually have a bash script which I run locally to do this, but it should probably be part of the `make test` process as well.

```bash
#!/bin/bash
FILES=($(ls examples/*.go | sed -e 's/examples\///'))

for file in "${FILES[@]}"
do
  echo $file
  go build -o /tmp/$file examples/$file
done
```

**Comment by saulshanabrook** [comment]
@zankich ahh thats pretty cool.
