### ISSUE TITLE
Bad URL in Sphero install documentation

### ISSUE THREAD

**Issue by cjqian** [hybridgroup/gobot#204]
http://gobot.io/documentation/drivers/sphero/

Install the library with:
``` go get github.com/hybridgroup/gobot && go install github.com/hybridgroup/platforms/sphero```

should be

Install the library with:
``` go get github.com/hybridgroup/gobot && go install github.com/hybridgroup/gobot/platforms/sphero```

**Comment by deadprogram** [comment]
That has been corrected in https://github.com/hybridgroup/gobot-site/commit/68d1805c4a1856b1bb1e07169a5db80d82b4fb9b thank you for reporting!
