### ISSUE TITLE
Aggressive spam with firmata

### ISSUE THREAD

**Issue by joushou** [hybridgroup/gobot#219]
I haven't debugged this issue deeper, but making a simple robot with firmata, and making an analog reader with interval of 5 seconds causes the arduino to send aggressive rates of messages, which does not seem right (if I log in firmata/client.go@process, my stdout is spammed to death, and the TX light is practically permanently lit on the arduino).

Unsure if bug in firmware or gobot, or if but at all.

**Comment by deadprogram** [comment]
Hi, @joushou 

Using Firmata requires polling the serial port that is connected to the Arduino. THis is needed to determine if there are any pin changes, new i2c data, etc. As such, a fairly constant rate of communication is required with the serial port being used when using the Firmata protocol.

Please let me know if I can provide any further info, and reopen this issue if so. Thanks!

**Comment by joushou** [comment]
If I read the implementation correctly, you're not supposed to poll any of that. REPORT_DIGITAL is supposed to handle info about digital pins, I2C will report back if it's set to continous mode, etc., etc.. It's meant to be a push protocol, not polling.

Of course, I may be wrong, but that's what it looks like from the StandardFirmata Arduino implementation.

**Comment by joushou** [comment]
Also, I can't reopen issues. :/

**Comment by deadprogram** [comment]
Hi @joushou the implementation of the Firmata's digital and analog readers should have been awaiting report notifications for a while now. I did not testing myself recently and did not see the behavior you are describing. This time I really am going to close, please open a new issue if you see this behavior. Thanks again!

**Comment by joushou** [comment]
Sounds good to me. I'll reopen if I get around to testing and trying this again.
