### ISSUE TITLE
support camera 

### ISSUE THREAD

**Issue by brunoksato** [hybridgroup/gobot#227]
Gotbot support camera work with arduino

example drive camera OV9655 

have support ? thanks

**Comment by deadprogram** [comment]
Hi, @brunoksato we currently use the "Firmata" protocol with the Arduino platform. You would need to either extend Firmata, or use some different custom firmware on the Arduino, to support the digital interface used by most of these cameras (SCCB).

We do have OpenCV support, but that is running on a Linux system, not on the Arduino itself. Perhaps that might suit your needs?

**Comment by brunoksato** [comment]
i'm need communication for camera + motor + arduino, need to make the communication of these three synchronous way, one depending on the other, using opencv the Gobot I can integrate with Arduino Gobot?

**Comment by deadprogram** [comment]
If in that scenario you will have a Linux single-board computer controlling everything, then yes. Since you cannot run Golang on the Arduino itself, that is the only way to do what you describe.

**Comment by deadprogram** [comment]
@brunoksato did my last answer address your question?

**Comment by brunoksato** [comment]
Sorry delay, yes resolved ! 

Thanks
