### ISSUE TITLE
Make default PR base branch

### ISSUE THREAD

**Issue by trevrosen** [hybridgroup/gobot#233]
This is a request to please reset this repo so that the default for PR merges will be dev, per the contributing guide. This will reduce the chance of making dud PRs against master.

**Comment by deadprogram** [comment]
Done. Thanks for the reminder, I've messed up a few times on this myself.

**Comment by trevrosen** [comment]
So... should I close this issue now? :smiley_cat:

**Comment by deadprogram** [comment]
If you are satisfied it is complete, then yes. :family:

**Comment by trevrosen** [comment]
:+1:
