### ISSUE TITLE
Parrot Rolling Spider support ?

### ISSUE THREAD

**Issue by deadjoe** [hybridgroup/gobot#234]
Hi this is amazing project to a golang developer as well as a robot fan.

Just wonder if any plan to support the Rolling Spider from Parrot ? 

thanks,

joe

**Comment by deadprogram** [comment]
Hi, @deadjoe we will need BLE support in order to implement support for that platform. We're working on it...

**Comment by deadjoe** [comment]
Awesome !

**Comment by deadjoe** [comment]
Hi , just want to know if Parrot Rolling Spider supported yet?

**Comment by deadprogram** [comment]
Hi @deadjoe we are just adding experimental support in the ble-wip branch. Currently works on OS X but we're trying to get it working on Linux as well.

**Comment by deadjoe** [comment]
Thanks , cool !

**Comment by deadprogram** [comment]
Since I originally responded to this issue, we released v0.12.x that includes the experimental BLE support and support on OSX. The `dev` branch also includes the Linux support for the minidrone, which will also be released soon.

**Comment by deadjoe** [comment]
Thanks, 

I saw the BLE support in the latest release. I am looking for  documents or examples about the BLE support with my rolling spider ? Can't find it from the gobot website and appreciate if you can give a clue.

**Comment by deadprogram** [comment]
The docs are now updated with this info. Thanks, everyone.
