### ISSUE TITLE
Arduino MPU6050 

### ISSUE THREAD

**Issue by sgilani** [hybridgroup/gobot#239]
I get only back this when i run the Go Prog. on Windows, i checked the Adress with I2C Scanner for Adruino and i get back 0x68, some where the communication is broken. 

Plattform Windows 8.1 & Adruino Mega 2560 and the RX/TX Light are On on the Board when i run "go run test_mpu.go", COM Port is set to 57600.

Connection: Adruino to MPU6050 (Not Sparkfun Version)

ADRUINO - 5V to MPU6050 VCC
ADRUINO - GND to MPU6050 GND
ADRUINO - SCL 21 to MPU6050 SCL
ADRUINO - SDA 20 to MPU6050 SDA

Any ideas? 

Accelerometer {0 0 0}
Gyroscope {0 0 0}
Temperature 0

package main

import (
  "fmt"
  "time"

  "github.com/hybridgroup/gobot"
  "github.com/hybridgroup/gobot/platforms/firmata"
  "github.com/hybridgroup/gobot/platforms/i2c"
)

func main() {
  gbot := gobot.NewGobot()

  firmataAdaptor := firmata.NewFirmataAdaptor("firmata", "COM4")
  mpu6050 := i2c.NewMPU6050Driver(firmataAdaptor, "mpu6050")

  work := func() {
    gobot.Every(300*time.Millisecond, func() {
      fmt.Println("Accelerometer", mpu6050.Accelerometer)
      fmt.Println("Gyroscope", mpu6050.Gyroscope)
      fmt.Println("Temperature", mpu6050.Temperature)
    })
  }

  robot := gobot.NewRobot("mpu6050Bot",
    []gobot.Connection{firmataAdaptor},
    []gobot.Device{mpu6050},
    work,
  )

  gbot.AddRobot(robot)

  gbot.Start()
}

**Comment by sgilani** [comment]
By the end i solved my problem in another way for get the values in go:

1.: Adruino Uploaded the MPU6050 RA Example
2.: Done a conection with serial to get the values

package main

import (
         serial "github.com/tarm/serial"
         "log"
				 
)

func main() {
         conf := new(serial.Config)
         conf.Name = "COM4"
         conf.Baud = 57600
				 conf.ReadTimeout = 0

         sc, err := serial.OpenPort(conf)
         if err != nil {
                 log.Fatal(err)
         }

         buf := make([]byte, 1024)

         for {
                 n, err := sc.Read(buf)
                 if err != nil {
                         log.Fatal(err)
                 }
                 log.Printf("%s\n", buf[:n])
         }
}

**Comment by sgilani** [comment]
UPDATE:

In Release 8.2 the MPU6050 Driver is Broken. In Version 8.1 it works more or less, the Values are not refreshed, after removing in github.com/hybridgroup/gobot/platforms/i2c/mpu6050_driver.go this part:

	// setSleepEnabled
	if err = h.connection.I2cWrite([]byte{MPU6050_RA_PWR_MGMT_1,
		MPU6050_PWR1_SLEEP_BIT,
		0}); err != nil {
		return
	}

All looks fine and i have all my values. Later i will make a diff between 8.2 and 8.1 to see what is broken and why.

Maybe for the moment it is helpfull for other users.

**Comment by deadprogram** [comment]
Hi, @sgilani 

Can you please try this code in substitute for the `initialize` method?

```
func (h *MPU6050Driver) initialize() (err error) {
	if err = h.connection.I2cStart(mpu6050Address); err != nil {
		return
	}

	// setClockSource
	if err = h.connection.I2cWrite(mpu6050Address, []byte{MPU6050_RA_PWR_MGMT_1,
		MPU6050_PWR1_CLKSEL_BIT,
		MPU6050_PWR1_CLKSEL_LENGTH,
		MPU6050_CLOCK_PLL_XGYRO}); err != nil {
		return
	}

	// setFullScaleGyroRange
	if err = h.connection.I2cWrite(mpu6050Address, []byte{MPU6050_RA_GYRO_CONFIG,
		MPU6050_GCONFIG_FS_SEL_BIT,
		MPU6050_GCONFIG_FS_SEL_LENGTH,
		MPU6050_GYRO_FS_250}); err != nil {
		return
	}

	// setFullScaleAccelRange
	if err = h.connection.I2cWrite(mpu6050Address, []byte{MPU6050_RA_ACCEL_CONFIG,
		MPU6050_ACONFIG_AFS_SEL_BIT,
		MPU6050_ACONFIG_AFS_SEL_LENGTH,
		MPU6050_ACCEL_FS_2}); err != nil {
		return
	}

	return nil
}
```

Please let me know if that works for you!

**Comment by sgilani** [comment]
HI deadprogramm,

thanks for help, this is the result after implentation, no values.

Accelerometer {0 0 0}
Gyroscope {0 0 0}
Temperature 0

**Comment by sgilani** [comment]
Maybe also helpful for debuging:

This freezes the values:

h.adaptor().I2cWrite([]byte{MPU6050_RA_PWR_MGMT_1,
		MPU6050_PWR1_SLEEP_BIT,
		0})

but when i remove just MPU6050_RA_PWR_MGMT_1 so the part looks like this:

h.adaptor().I2cWrite([]byte{
		MPU6050_PWR1_SLEEP_BIT,
		0})

I get again refreshed values, but some are missing:

Accelerometer {20268 -120 14648}
Gyroscope {-5008 -747 0}
Temperature 0

Gyro part 3 and Temp are lost somewhere... really strange

**Comment by sgilani** [comment]
Solved for v.8.1, change this 

const MPU6050_PWR1_SLEEP_BIT = 6

to this

const MPU6050_PWR1_SLEEP_BIT = 0

then we can also use the setSleepEnabled part without troubles, to get the right values:

Accelerometer {16472 -680 1772}
Gyroscope {-3872 406 -13133}
Temperature 35
Accelerometer {17472 408 4456}
Gyroscope {-3888 -3898 -3417}
Temperature 33
Accelerometer {16836 -120 856}
Gyroscope {-3824 -625 238}
Temperature 35

**Comment by deadprogram** [comment]
According to the MPU6050 docs I could find:

```
Get sleep mode status. Setting the SLEEP bit in the register puts the device into very low power sleep mode. In this mode, only the serial interface and internal registers remain active, allowing for a very low standby current. Clearing this bit puts the device back into normal mode. To save power, the individual standby selections for each of the gyros should be used if any gyro axis is not used by the application. 
```

So perhaps, a better thing would be to add a new constant `const MPU6050_PWR1_ENABLE_BIT = 0` and use that. I'd love a a PR that did that! :)

**Comment by sgilani** [comment]
You are right and i like your idea :) i will change it and share it.

**Comment by deadprogram** [comment]
Hi, @sgilani did you ever have a chance to work up a PR with this? :)
