### ISSUE TITLE
Gobot spawns thousands of goroutines causing it to crash everytime

### ISSUE THREAD

**Issue by osiloke** [hybridgroup/gobot#248]
Not sure why robot spawns that many threads (assuming, multiple goroutines are running), but it seems to be spawning threads exponentially. I'm using the current master, connecting to an arduino  uno and just blinking the led (based on the example). It spans over 2150 grooviness. That seems a bit too weird. Any suggestions would be great, i'm also taking a look at gobots source.
```
func setupArduino() *gobot.Robot {
	//Arduino bot
	device := findArduino()
	arduino := firmata.NewFirmataAdaptor("arduino", device)
  statusLed := gpio.NewLedDriver(arduino, "led", "13") 

	work := func() {
    gobot.Every(1*time.Second, func() {
      statusLed.Toggle()
    })
  }

  return gobot.NewRobot("arduinoExpansion",
    []gobot.Connection{arduino},
		[]gobot.Device{statusLed},
    work,
  )
}
func main() {
  gbot := gobot.NewGobot()
  gbot.AddRobot(setupArduino())

  gbot.Start()
}
```

**Comment by osiloke** [comment]
reinstalled gobot, and it stopped spawning infinite goroutines. I must not have been using the latest master. Although, i now notice that a signal interrupt (ctrl+c) does not shut it down

**Comment by trevrosen** [comment]
@osiloke have a look at the commits referenced in #216 and you should have a sense of how to get the behavior you're looking for. Thanks for using Gobot!
