### ISSUE TITLE
sample code for Raspberry Pi with Grove LCD

### ISSUE THREAD

**Issue by TheInsideMan** [hybridgroup/gobot#249]
Hello folks,

Can I get an example on how to use the Raspberry Pi with Grove LCD ?

**Comment by TheInsideMan** [comment]
this seems to be the best tutorial available http://dev.classmethod.jp/hardware/edison/intel-edison-use-lcd-rgb-backlight/

**Comment by TheInsideMan** [comment]
hi @mattetti do you have any sample code you can share ?

**Comment by TheInsideMan** [comment]
update... I easily adapted edison_grove_lcd.go from the example folder. Works perfectly with Raspberry Pi. Thanks again guys.

**Comment by mattetti** [comment]
@TheInsideMan here is an example app using the grove lcd: https://github.com/mattetti/eddie

**Comment by TheInsideMan** [comment]
@mattetti Perfect, many thanks!
