### ISSUE TITLE
LED pin 18 not blinking with raspb

### ISSUE THREAD

**Issue by TheInsideMan** [hybridgroup/gobot#250]
Hello, Im trying to get a LED on pin 18 to flash with a raspberry pi 2 with the following code... any help appreciated...

error: Starting work... open /sys/class/gpio/gpio24/direction: permission denied
```
gbot := gobot.NewGobot()
r := raspi.NewRaspiAdaptor("raspi")
led := gpio.NewLedDriver(r, "led", "18")

work := func() {
   gobot.Every(1*time.Second, func() {
      err := led.Toggle()
      if err != nil {
	      fmt.Println(err.Error())
      }
   })
}

robot := gobot.NewRobot("blinkBot",
   []gobot.Connection{r},
   []gobot.Device{led},
   work,
)

gbot.AddRobot(robot)
gbot.Start()
```

I've got pi-blaster deamon running.

Im able to get the LED flashing using python so I know it isnt a hardware issue.
![rasp2](https://cloud.githubusercontent.com/assets/3842823/12035879/a0b9a23a-ae38-11e5-84a1-07e69cf39e3e.jpg)

**Comment by TheInsideMan** [comment]
I tried to run $ sudo ./aambr 

This does stop the error printing but still no flashing LED :(

**Comment by deadprogram** [comment]
Hi, @TheInsideMan thank you for the photo. Looks to me line you are plugged into pin labeled on board number 12, which maps to Linux BCM18. When programming using Gobot, you just use whatever the board is labelled, and we do the mapping for you, so you code should be using "12" for the pin number. We probably need to make a bigger deal of explaining this on every platform.

**Comment by TheInsideMan** [comment]
thank you @deadprogram thats working now! much appreciated. Let take the opportunity to thank you fro you work on Gobot.

**Comment by Depado** [comment]
Hi, yes that sure needs some explanation ! 
I had the exact same issue as you @TheInsideMan, thanks a lot for the clarification @deadprogram :D
(When I say, exact same issue, we have the exact same setup and approximately quite the same code haha)

**Comment by gherlein** [comment]
Probably need some error handling if you call gpio.NewLedDriver with a pin that is not a GPIO pin...

**Comment by nilskuhn** [comment]
Where do you see labels on the raspberry gpio pins? 
I'm using version 2 B of the pi.

**Comment by deadprogram** [comment]
I highly recommend https://pinout.xyz/

**Comment by nilskuhn** [comment]
thx, I already found it in the meanwhile
