### ISSUE TITLE
Analog joystick lag

### ISSUE THREAD

**Issue by kittuov** [hybridgroup/gobot#266]
### How to reproduce the issue:
run example provide and move the analog stick of device very fast (Basically producing events faster than poll interval) the last state is reflected after a lag. the lag is even prominent if two sticks are used at the same time. 
### Possible fix:
in ```go func (j *JoystickDriver) Start() (errs []error) ``` the goroutine can be modified as 
>Note:  *this leads to yet another bug*
```go
go func() {
		for {
			event := j.poll()
			for {
				if tem:=j.poll();tem==nil{
					break
				}else {
					event = tem
				}
			}
			if event != nil {
				if err = j.handleEvent(event); err != nil {
           ...

The code above is actually gets the latest event and lets the gobot process that.
### Bug in this code:
* If two axis are moved at the same time, only one of the event is processed. 
* some button events also may not be processed.

#### TODO: In case of stacked events, loop through all new events and, 
1. get latest of all axis events and processes them. 
2. get all of button events and process them.
3. *No idea what a hat is*

**Comment by deadprogram** [comment]
This was fixed by @kittuov https://github.com/hybridgroup/gobot/commit/e84326b129610719bbad88ab3d596411b3839e7e
