### ISSUE TITLE
EMW3165 microcontroller with WLAN

### ISSUE THREAD

**Issue by rahulpilani** [hybridgroup/gobot#270]
Would be great if gobot could support this chip as well. 

http://www.seeedstudio.com/depot/EMW3165-p-2488.html

**Comment by gen2thomas** [comment]
This is a microcontroller with WLAN. The controller is the [STM32F411CE](https://www.st.com/en/microcontrollers-microprocessors/stm32f411ce.html). If the controller has support for firmata protocol, it should work.

**Comment by gen2thomas** [comment]
I think, the [TinyGo](https://github.com/tinygo-org/tinygo) project is the right and better place to request support for new microcontrollers. So I'm going to close this issue now.
