### ISSUE TITLE
Intel Edison read specific i2c register

### ISSUE THREAD

**Issue by allanglen** [hybridgroup/gobot#272]
I am writing a driver for the MPU9150 IMU.  I am attempting to read a byte from a specific register and am always getting back the value from the first register on the device.

The sysfs i2c implementation sets the command byte to 0 for all reads:
https://github.com/hybridgroup/gobot/blob/dev/sysfs/i2c_device.go#L103

Per the documentation here (https://www.kernel.org/doc/Documentation/i2c/smbus-protocol), an I2C_SMBUS_I2C_BLOCK_DATA operation uses the command byte to set the starting register for the read but that is always set to 0.

An I2C_SMBUS_READ_BYTE operation will use the register from a previous write but not I2C_SMBUS_I2C_BLOCK_DATA.

Are all drivers that currently implemented just happening to be reading from the first register or am I missing something obvious?

**Comment by deadprogram** [comment]
Looks like this is an oversight that does not impact you if you are using an i2c adaptor that does not support the block data reads.

The solution is probably use the first byte of `b` as the register for that call. What do you think?

**Comment by deadprogram** [comment]
Hi @allanglen looked at this with fresh eyes, and I see that the `Write()` command is doing the right thing: https://github.com/hybridgroup/gobot/blob/dev/sysfs/i2c_device.go#L128

I am going to make a similar change to `Read()`, would you be able to test this out on your hardware config?

**Comment by deadprogram** [comment]
Hi @allanglen this should now be fixed in the `dev` branch.
