### ISSUE TITLE
Custom Mavlink Messages

### ISSUE THREAD

**Issue by enkoder** [hybridgroup/gobot#279]
How was the mavlink/common.go file generated and does it support custom mavlink messages?

**Comment by deadprogram** [comment]
Hi @enkoder 

We used our own fork of mavlink (https://github.com/hybridgroup/mavlink) that was able to generate the golang code. 

Recently we've been evaluating some of the newer Golang mavlink libs that are looking interesting, with an eye at using that in the Gobot implementation.

**Comment by enkoder** [comment]
Thanks @deadprogram.
