### ISSUE TITLE
gobot.io: High-exposure link 404 on the Getting Started page

### ISSUE THREAD

**Issue by lunakid** [hybridgroup/gobot#280]
"Writing And Running Gobot Robots

With the Gobot packages installed, you're ready to start writing your own code. You can take a look at some of the examples below, or read the guide page on *[Working with Robots](https://gobot.io/documentation/guides/working-with-robots/)*."

**Comment by deadprogram** [comment]
Hi, @lunakid thanks for pointing that out. The old invalid link has been removed here https://github.com/hybridgroup/gobot-site/commit/060f18ae26485ffddedc2a1b2490bdf3f6c853d6 and the site has been updated.
