### ISSUE TITLE
why is the pin number a string?

### ISSUE THREAD

**Issue by nhooyr** [hybridgroup/gobot#282]
Why do functions such as `gpio.NewLedDriver(rasp, "led", "18")` take the pin number as a string instead of an int?

**Comment by deadprogram** [comment]
Hi @nhooyr 

Some platforms such as the Beaglebone Black label their pins using formats such as "P8_3". When using Gobot, we make it possible to use whatever the board itself is labeled, then we translate that to whatever the underlying interface expects. Hope that helps!

**Comment by nhooyr** [comment]
alright, thanks
