### ISSUE TITLE
raspberry pi does not support analog

### ISSUE THREAD

**Issue by nhooyr** [hybridgroup/gobot#284]
https://gobot.io/documentation/drivers/analog-sensor/

It says below that the raspberry pi is supported but the pi has no analog pins?

**Comment by deadprogram** [comment]
Hi, @nhooyr you are correct, that is an error in that docs page. As you pointed out, the raspi has no AIO.

If you have a moment, would you mind opening an issue on https://github.com/hybridgroup/gobot-site

Thanks!

**Comment by deadprogram** [comment]
The docs are now updated with this info. Thanks, everyone.
