### ISSUE TITLE
parallax support?

### ISSUE THREAD

**Issue by bradleypeabody** [hybridgroup/gobot#285]
I know there are several factors this depends on, but is support for [Parallax Propeller boards](https://www.parallax.com/product/32810) on the roadmap anywhere?  I realize those boards are likely by default rather under powered (not enough memory) to run the Go runtime, but it should be possible with some caveats.  Maybe it's a stretch - but I just wanted to check and see if there was any existing interest.

**Comment by gen2thomas** [comment]
Hi @bradleypeabody, thanks for the idea to support Parallax boards. Gobot supports microcontrollers, which are compatible with firmata and digispark, which is connected by "littleWire". In the meantime, I think, the [TinyGo](https://github.com/tinygo-org/tinygo) project is the right and better place to request support for new microcontrollers.

I'm going to close this issue now.
