### ISSUE TITLE
hardware PWM for the raspberry pi

### ISSUE THREAD

**Issue by nhooyr** [hybridgroup/gobot#286]
gobot has support for software PWM via pi-blaster but no support for the pi's hardware PWM.

**Comment by deadprogram** [comment]
As the pi-blaster docs say "The technique used is extremely efficient: does not use the CPU and gives very stable pulses".

So, is this really needed?

**Comment by nhooyr** [comment]
No idea, just thought I'd mention it.

**Comment by deadprogram** [comment]
Furthermore, pi-blaster says it "uses the hardware PWM generator of the raspberry pi to get precise timings".

I think I will close this issue. Please reopen if from some further research you feel it is needed.
