### ISSUE TITLE
Platform request: ESP8266

### ISSUE THREAD

**Issue by AndreyS1** [hybridgroup/gobot#301]
Would be great if gobot could support this chip as well.

**Comment by icecrasher321** [comment]
Agree with him. With its brilliant and cheap iot capabilities, the ESP8266 would be a great addition.

**Comment by deadprogram** [comment]
This should be totally doable, by running StandardFirmataWiFi on the ESP8266, and then by passing a struct whihc is a `net/UDPConn` instead of a `tarm/goserial` in the `NewFirmataAdaptor` constructor, since both support `io.ReadWriteCloser`.

**Comment by olliephillips** [comment]
I have no idea what's involved here. But I use Espruino on ESP8266. Being able to use Go would be amazing. It's also worth mentioning ESP3212, which has started to ship, could be more significant in terms of impact than even the ESP8266 was/is

**Comment by deadprogram** [comment]
Hi @olliephillips running Golang directly on MCUs is not currently possible. However, in similar fashion to how Espruino is a stripped-down JavaScript, there are a couple of projects trying to get a Golang-like syntax running on the MCU itself. Check out https://github.com/ziutek/emgo

**Comment by olliephillips** [comment]
@deadprogram thanks I'll check out that link. In terms of gobot.io can we currently treat the ESP8266 as an arduino platform? This was where my thinking started out.

**Comment by deadprogram** [comment]
@olliephillips yes, it can be treated as an Arduino if you are running the Firmata firmware on it. However, we will still need a "serial over TCP/UDP" adaptor for Gobot.

**Comment by deadprogram** [comment]
Hi everyone. Just commited some work to the `dev` branch with a preliminary implementation of `TCPAdaptor` for Firmata. Check out https://github.com/hybridgroup/gobot/blob/dev/examples/wifi_firmata_blink.go which works with my NodeMCU 1.0 ESP8266 running WifiFirmata.

**Comment by deadprogram** [comment]
Experimental support for this was just released as part of v1.1.0. Now closing.
