### ISSUE TITLE
mqtt from git.eclipse.org is not accepted any more.

### ISSUE THREAD

**Issue by johanhenselmans** [hybridgroup/gobot#313]
Doing : go get -d -u github.com/hybridgroup/gobot/...
resulted in:
package git.eclipse.org/gitroot/paho/org.eclipse.paho.mqtt.golang.git: cannot download, git://git.eclipse.org/gitroot/paho/org.eclipse.paho.mqtt.golang uses insecure protocol

This was caused by platforms/mqtt/mqtt_adaptor.go
changing (in platforms/mqtt/mqtt_adaptor.go)

import (
	"git.eclipse.org/gitroot/paho/org.eclipse.paho.mqtt.golang.git"
	"github.com/hybridgroup/gobot"
)

to: 
import (
	"github.com/eclipse/paho.mqtt.golang"
	"github.com/hybridgroup/gobot"
)

Solved this.

**Comment by deadprogram** [comment]
Hi @johanhenselmans thanks for pointing this out. A PR with this fix would be gratefully accepted :)

**Comment by deadprogram** [comment]
Hi @johanhenselmans this has been fixed as part of https://github.com/hybridgroup/gobot/commit/17cc57d9d1844a3fc97234fd8ae2304552cb9e12

I will leave this issue open until that code is released.

**Comment by deadprogram** [comment]
This code is now in PR https://github.com/hybridgroup/gobot/pull/316

**Comment by deadprogram** [comment]
This has now been merged into the `dev` branch. Please re-open if needed.
