### ISSUE TITLE
go installation problem, osx 10.12.1

### ISSUE THREAD

**Issue by alexander-yun** [hybridgroup/gobot#335]
go get -d -u github.com/hybridgroup/gobot/...                                                 1:11
package github.com/hybridgroup/gobot/...: mkdir /home/username: operation not supported

**Comment by deadprogram** [comment]
Hi, @alexander-yun 

What does the "1:11" in your installation signify? In any case, please make sure you have followed the official Golang install instructions for OSX https://golang.org/doc/install

Seems like this is a problem with your Golang installation, not with Gobot itself.

Hope that helps!

**Comment by alexander-yun** [comment]
Hi, deadprogram
1:11 is time when I run the command "go get -d -u github.com/hybridgroup/gobot/..."
Your answer helped me. 
In  Golang install instructions official page I review again environment variables and find mistake.
Now install works.

Thank you.
