### ISSUE TITLE
bb8 driver missing NewDriver function

### ISSUE THREAD

**Issue by nickryand** [hybridgroup/gobot#346]
Trying to build on OSX and I get the following error while building:

```
$ GODBUG=cgocheck=0 go build -o /tmp/bb8 examples/bb8.go
# command-line-arguments
examples/bb8.go:14: undefined: bb8.NewDriver
$
```

Is NewDriver missing from the bb8_driver or am I doing something wrong? 

Attempting to build on:
```
$ go version
go version go1.7.3 darwin/amd64
```

I am building from the latest available via the `go get` instructions.

**Comment by deadprogram** [comment]
Hi, @nickryand thanks for the report. Some code was indeed missing, and has been updated. You can now get the package with the `-u` option and the updated code is available.

Please reopen if needed, and thanks again.

**Comment by nickryand** [comment]
Working good now! Thanks for the quick response!
