### ISSUE TITLE
new Platform, Pine64

### ISSUE THREAD

**Issue by jwhitcraft** [hybridgroup/gobot#362]
Hello,

I have one of the Pine64 boards and I would love to find a use for it,  Could support be added for it?

https://www.pine64.org/
http://wiki.pine64.org/index.php/Main_Page

Thanks.

**Comment by deadprogram** [comment]
We do not have one of these boards, but looks like creating an adaptor for the pin mappings would not be too difficult. Looks like this web page has the information that would be needed: http://joey.hazlett.us/pine64/pine64_pins.html

A PR that added this support would be gladly accepted.
