### ISSUE TITLE
C.H.I.P. Pro?

### ISSUE THREAD

**Issue by brandonblock** [hybridgroup/gobot#366]
Curious if anyone has explored platform compatibility with the [C.H.I.P. Pro](https://getchip.com/pages/chippro) version. I haven't ordered one yet, but I assume the pins have different names at the very least.

**Comment by deadprogram** [comment]
Hi @brandonblock we have just added preliminary support for C.H.I.P. Pro in the `dev` branch here: https://github.com/hybridgroup/gobot/commit/8cfb7db7cdcb54d1978b4cb3c84b075c5f55ad6f

Anyone who has one and wants to test things out, your feedback and bug reports are appreciated!

**Comment by deadprogram** [comment]
Support for the C.H.I.P. Pro has just been released as part of Gobot 1.5 so please open a new issue with any specifics.

Thanks!
