### ISSUE TITLE
Re-authorize Coveralls

### ISSUE THREAD

**Issue by Zanadar** [hybridgroup/gobot#368]
Hey there!

I was looking through the project to see if I might add test coverage, and I saw the following in coveralls, when I clicked through to look at the specific coverage of a file:

![screen shot 2017-02-15 at 6 46 12 pm](https://cloud.githubusercontent.com/assets/5925347/23000584/30d0882c-f3af-11e6-8c7a-ad18d398e352.png)

**Comment by deadprogram** [comment]
Thanks for reporting this @Zanadar seems like a coveralls problem, which we have reported.

I'll update this issue once it is resolved.

**Comment by deadprogram** [comment]
Seems to be same problem as https://github.com/lemurheavy/coveralls-public/issues/596#issuecomment-138922490

**Comment by deadprogram** [comment]
@Zanadar doing some experimenting with codecov.io check out https://codecov.io/gh/hybridgroup/gobot see what you think...

**Comment by deadprogram** [comment]
OK, we've just "officially" switched to codecov.io :)

Closing this issue, please re-open if needed.
