### ISSUE TITLE
Broken link on website

### ISSUE THREAD

**Issue by BChip** [hybridgroup/gobot#383]
I went over to: https://gobot.io/documentation/platforms/digispark/

If you click on the API Reference button, it takes you to a broken link: https://godoc.org/gobot.io/x/gobot/platforms/digispark#DigisparkAdaptor

**Comment by deadprogram** [comment]
Hi @BChip this commit to the docs site https://github.com/hybridgroup/gobot-site/commit/fa6d1f638a08dcfab668653cf5239b4052559c2b corrects this problem.

Thank you!
