### ISSUE TITLE
SPI Support?

### ISSUE THREAD

**Issue by johanhenselmans** [hybridgroup/gobot#388]
Is there any plan to add SPI support?

**Comment by deadprogram** [comment]
We have some plans for this... more on that soon.

**Comment by sir-buckyball** [comment]
is it soon yet?

**Comment by deadprogram** [comment]
There is progress indeed!

Please checkout the latest work here: https://github.com/hybridgroup/gobot/tree/dev/drivers/spi

**Comment by deadprogram** [comment]
Initial SPI support has now been released as part of https://github.com/hybridgroup/gobot/releases/tag/v1.7.0 so I an going to close this issue. Please repoen if needed.
