### ISSUE TITLE
Website Navigation Menu News highlights wrong item

### ISSUE THREAD

**Issue by DavidMcDonnel** [hybridgroup/gobot#397]
When clicking on the news category [https://gobot.io/news/](url), the "Resources" item of the navigation menu is highlighted.

**Comment by deadprogram** [comment]
Hi @DavidMcDonnel thank you for reporting this. It has been corrected by https://github.com/hybridgroup/gobot-site/commit/6450b3674ceec459026c25f89f860ee8094f16b1

Now closing. Thanks again.
