### ISSUE TITLE
Raspberry Pi 3 Completely Unresponsive

### ISSUE THREAD

**Issue by SafaiWeb** [hybridgroup/gobot#399]
I'm sorry if there is something I am not seeing in here, I'm really trying to use this framework and any help would be appreciated:

I have had issues with this for days using a RP3 and the newest version of Raspbian.

I copy/pasted the program from the platform page at https://gobot.io/documentation/platforms/raspi/.

I set up the circuit exactly as shown in the led light diagram.

The program compiled without errors on MacOSX (cross-compiled with GOARM=7 GOARCH=arm GOOS=linux).

When I run the program from the Pi (transferred with a USB drive), I get no response. I do have to use chmod to execute the program.

I tested the circuit against one of the power pins, and the LED lights up.

But, when used with the GPIO pins, I can't get so much as a flicker.  

Any suggestions or am I just going crazy?

**Comment by deadprogram** [comment]
Hello, @SafaiWeb perhaps you can upload a photo of your exact setup, in particular your circuit.

**Comment by SafaiWeb** [comment]
Thank you so much, I feel like it has to be something very silly on my part:

![img_20170330_104050](https://cloud.githubusercontent.com/assets/20464252/24509974/e05fee3e-1535-11e7-8377-7848296cb534.jpg)
![img_20170330_104039](https://cloud.githubusercontent.com/assets/20464252/24509989/e9adbb6a-1535-11e7-9c0c-305c45a5d936.jpg)
![img_20170330_104021](https://cloud.githubusercontent.com/assets/20464252/24510000/f10e6a9e-1535-11e7-950a-cbeda49ffa0a.jpg)

**Comment by deadprogram** [comment]
Looks like the LED is reversed in that photo. The flat side should be GND (negative). Normally I use a black wire to indicate ground, and use colors for pins. I reserve red for power.

Hope that helps!

**Comment by SafaiWeb** [comment]
I have tried it in both directions just to be sure :(

**Comment by deadprogram** [comment]
It will only work in one direction, that is for sure! :) Flat means GND.

**Comment by deadprogram** [comment]
Also, looks like you are using a 1K ohm resistor. You might want to try 270 ohm instead.

**Comment by SafaiWeb** [comment]
Have now tried a different resistor.  Have tried a different RP3.  No response.

Took circuit and switched to an arduino UNO. Followed instructions, used Gort. Uploaded Firmata, copy-pasted led blinking program.  No response.  The only discernable difference between the arduino and the RP3 is that when I execute the compiled program for the RP3 the terminal says "starting work..." before not responding, whereas with the arduino it says "starting connection firmata...on port...." before giving me a new command prompt and also not responding.

I'm as lost as a lamb in a snowstorm as to what could be wrong.

**Comment by SafaiWeb** [comment]
I also attached a PIR Motion Sensor to both the PI and the Arduino with the hopes of printing a line on the screen when motion was detected.  The Pi gave no response to either motion or lack of motion.

The Arduino returns a new command prompt, so there was no way to print to the terminal.  

Given the strange behavior of lights, and inability of motion sensing technology to detect me, current working theory is that I am a vampire.

**Comment by deadprogram** [comment]
Hi @SafaiWeb I'm not exactly sure what you mean by "The Arduino returns a new command prompt, so there was no way to print to the terminal."

Perhaps bringing in both an Arduino and other sensors into the mix might be clouding your original issue, as opposed to clearing it. Not sure on that, perhaps it is helping establish a baseline.

In any case, a few more basic questions:
- What version of OS X are you using on your desktop machine?
- What version of Golang do you have installed?
- How exactly did you load Fimata onto your Arduino?
- Which Arduino model are you using?
- What is the command line you are using to run the firmata_blink.go program?

**Comment by SafaiWeb** [comment]
I wasn't sure if it was helpful to change up the hardware or not. I thought there might be a potential defect in my actual pi, but it seems my issue is not there. 

1. MacOS Sierra. I have also tried using an Ubuntu 14.04 installation on a separate computer. 
2. I am using Golang 1.8. Installed via the binary on the Go project webpage on the mac. Installed via gvm on tge ubuntu machine
3. I uploaded with gort using the "gort arduino upload firmata /dev/ttyACM0". As this is the default address I also tried it once without the /dev/ttyACM0. This was the address given by gort scan serial. I really like Gort, by the way. 
4. Arduino UNO R3. 
5. Go run firmata_blink.go

**Comment by deadprogram** [comment]
If you are running the firmata_blink.go from your OSX machine to the connected Arduino, you would need to change up the serial interface name here https://github.com/hybridgroup/gobot/blob/master/examples/firmata_blink.go#L16 to match the name of whatever serial port your Arduino is mapped to on OS X.

**Comment by SafaiWeb** [comment]
I am running it on my Ubuntu machine, gort scan serial gives me the address [/dev/ttyACM0] as the address for my arduino.

**Comment by deadprogram** [comment]
Ubuntu happens to be my own preferred desktop OS. Perhaps permissions related? Try building, and then execute your program using sudo.

**Comment by deadprogram** [comment]
You probably will need to run your code on the raspi using sudo as well, unless you have added udev rules to give yourself whatever needed permissions to read/write to GPIO.

**Comment by deadprogram** [comment]
OK so I have a solution now thanks to a tip from @fivdi to ensure that the GPIO exports have correctly happened before trying to use the GPIO pins. This addresses the issue when running as a normal user.

The code is now in the `dev` branch @SafaiWeb if you want to try it out on your raspi. I will leave this issue open until this code has made it into the next release.

Thanks you @SafaiWeb for pointing this problem out.

**Comment by trevrosen** [comment]
@deadprogram just chiming in to say I think this export check is a great idea and something that has bitten me in the past, so I'm excited to see it land on mainline.

**Comment by deadprogram** [comment]
This code has now been released as part of Gobot 1.4 so I am now closing this issue. Please reopen if needed. Thank you everyone!
