### ISSUE TITLE
Having issues installing firmata platform features into Win10 system

### ISSUE THREAD

**Issue by JDogHerman** [hybridgroup/gobot#429]
I am attemting to install the firmata features following the steps listed [here](https://gobot.io/documentation/platforms/arduino/) and I am getting an error about not enough arguments. 

```
go get -d -u gobot.io/x/gobot/... && go install gobot.io/x/gobot/platforms/firmata
# gobot.io/x/gobot/sysfs
go\src\gobot.io\x\gobot\sysfs\i2c_device.go:88: undefined: syscall.SYS_IOCTL
go\src\gobot.io\x\gobot\sysfs\i2c_device.go:102: undefined: syscall.SYS_IOCTL
go\src\gobot.io\x\gobot\sysfs\i2c_device.go:219: undefined: syscall.SYS_IOCTL
go\src\gobot.io\x\gobot\sysfs\syscall.go:34: not enough arguments in call to syscall.Syscall
        have (uintptr, uintptr, uintptr, uintptr)
        want (uintptr, uintptr, uintptr, uintptr, uintptr)
```
The issue seems to be with the 2nd command ``go install`` as the ``go get`` command run alone does not show an error. My version of windows is Windows 10 Pro v1607 Build 14393.1198

**Comment by deadprogram** [comment]
All you need is the:

```
go get -d -u gobot.io/x/gobot/...
```

Docs were already updated here, just awaiting the next release: https://github.com/hybridgroup/gobot/blob/dev/platforms/firmata/README.md#how-to-install

Thanks for the report.

**Comment by deadprogram** [comment]
Version 1.6.0 is now out, and includes documentation fixes for this. Now closing, please reopen if needed. Thank you!

**Comment by miko-code** [comment]
IM having the same issue on win 10  i did the go get as you can see.

but I'm receiving the same error as above 

>  PS C:\projects\go\src\temp> go build
> # gobot.io/x/gobot/platforms/ble
> ..\gobot.io\x\gobot\platforms\ble\ble_client_adaptor.go:189: undefined: defaultDevice
> # gobot.io/x/gobot/sysfs
> ..\gobot.io\x\gobot\sysfs\i2c_device.go:88: undefined: syscall.SYS_IOCTL
> ..\gobot.io\x\gobot\sysfs\i2c_device.go:102: undefined: syscall.SYS_IOCTL
> ..\gobot.io\x\gobot\sysfs\i2c_device.go:219: undefined: syscall.SYS_IOCTL
> ..\gobot.io\x\gobot\sysfs\syscall.go:34: not enough arguments in call to syscall.Syscall
>         have (uintptr, uintptr, uintptr, uintptr)
>         want (uintptr, uintptr, uintptr, uintptr, uintptr)
> 



GO  GET 
> C:\WINDOWS\system32>go get -v -d -u gobot.io/x/gobot/...
Fetching https://gobot.io/x/gobot?go-get=1
Parsing meta tags from https://gobot.io/x/gobot?go-get=1 (status code 200)
get "gobot.io/x/gobot": found meta tag main.metaImport{Prefix:"gobot.io/x/gobot", VCS:"git", RepoRoot:"https://github.com/hybridgroup/gobot"} at https://gobot.io/x/gobot?go-get=1
gobot.io/x/gobot (download)
github.com/hashicorp/go-multierror (download)
Fetching https://gobot.io/x/gobot/api?go-get=1
Parsing meta tags from https://gobot.io/x/gobot/api?go-get=1 (status code 404)
github.com/bmizerany/pat (download)
Fetching https://gobot.io/x/gobot/api/robeaux?go-get=1
Parsing meta tags from https://gobot.io/x/gobot/api/robeaux?go-get=1 (status code 404)
Fetching https://gobot.io/x/gobot/cli?go-get=1
Parsing meta tags from https://gobot.io/x/gobot/cli?go-get=1 (status code 404)
github.com/codegangsta/cli (download)
Fetching https://gobot.io/x/gobot/drivers/aio?go-get=1
Parsing meta tags from https://gobot.io/x/gobot/drivers/aio?go-get=1 (status code 200)
get "gobot.io/x/gobot/drivers/aio": found meta tag main.metaImport{Prefix:"gobot.io/x/gobot", VCS:"git", RepoRoot:"https://github.com/hybridgroup/gobot"} at https://gobot.io/x/gobot/drivers/aio?go-get=1
get "gobot.io/x/gobot/drivers/aio": verifying non-authoritative meta tag
Fetching https://gobot.io/x/gobot?go-get=1
Parsing meta tags from https://gobot.io/x/gobot?go-get=1 (status code 200)
Fetching https://gobot.io/x/gobot/drivers/gpio?go-get=1
Parsing meta tags from https://gobot.io/x/gobot/drivers/gpio?go-get=1 (status code 200)
get "gobot.io/x/gobot/drivers/gpio": found meta tag main.metaImport{Prefix:"gobot.io/x/gobot", VCS:"git", RepoRoot:"https://github.com/hybridgroup/gobot"} at https://gobot.io/x/gobot/drivers/gpio?go-get=1
get "gobot.io/x/gobot/drivers/gpio": verifying non-authoritative meta tag
Fetching https://gobot.io/x/gobot/drivers/i2c?go-get=1
Parsing meta tags from https://gobot.io/x/gobot/drivers/i2c?go-get=1 (status code 200)
get "gobot.io/x/gobot/drivers/i2c": found meta tag main.metaImport{Prefix:"gobot.io/x/gobot", VCS:"git", RepoRoot:"https://github.com/hybridgroup/gobot"} at https://gobot.io/x/gobot/drivers/i2c?go-get=1
get "gobot.io/x/gobot/drivers/i2c": verifying non-authoritative meta tag
github.com/sigurn/crc8 (download)
github.com/sigurn/utils (download)
Fetching https://gobot.io/x/gobot/sysfs?go-get=1
Parsing meta tags from https://gobot.io/x/gobot/sysfs?go-get=1 (status code 200)
get "gobot.io/x/gobot/sysfs": found meta tag main.metaImport{Prefix:"gobot.io/x/gobot", VCS:"git", RepoRoot:"https://github.com/hybridgroup/gobot"} at https://gobot.io/x/gobot/sysfs?go-get=1
get "gobot.io/x/gobot/sysfs": verifying non-authoritative meta tag
Fetching https://gobot.io/x/gobot/examples?go-get=1
Parsing meta tags from https://gobot.io/x/gobot/examples?go-get=1 (status code 404)
Fetching https://gobot.io/x/gobot/platforms/raspi?go-get=1
Parsing meta tags from https://gobot.io/x/gobot/platforms/raspi?go-get=1 (status code 200)
get "gobot.io/x/gobot/platforms/raspi": found meta tag main.metaImport{Prefix:"gobot.io/x/gobot", VCS:"git", RepoRoot:"https://github.com/hybridgroup/gobot"} at https://gobot.io/x/gobot/platforms/raspi?go-get=1
get "gobot.io/x/gobot/platforms/raspi": verifying non-authoritative meta tag
Fetching https://gobot.io/x/gobot/gobottest?go-get=1
Parsing meta tags from https://gobot.io/x/gobot/gobottest?go-get=1 (status code 404)
Fetching https://gobot.io/x/gobot/platforms/audio?go-get=1
Parsing meta tags from https://gobot.io/x/gobot/platforms/audio?go-get=1 (status code 200)
get "gobot.io/x/gobot/platforms/audio": found meta tag main.metaImport{Prefix:"gobot.io/x/gobot", VCS:"git", RepoRoot:"https://github.com/hybridgroup/gobot"} at https://gobot.io/x/gobot/platforms/audio?go-get=1
get "gobot.io/x/gobot/platforms/audio": verifying non-authoritative meta tag
Fetching https://gobot.io/x/gobot/platforms/beaglebone?go-get=1
Parsing meta tags from https://gobot.io/x/gobot/platforms/beaglebone?go-get=1 (status code 200)
get "gobot.io/x/gobot/platforms/beaglebone": found meta tag main.metaImport{Prefix:"gobot.io/x/gobot", VCS:"git", RepoRoot:"https://github.com/hybridgroup/gobot"} at https://gobot.io/x/gobot/platforms/beaglebone?go-get=1
get "gobot.io/x/gobot/platforms/beaglebone": verifying non-authoritative meta tag
Fetching https://gobot.io/x/gobot/platforms/ble?go-get=1
Parsing meta tags from https://gobot.io/x/gobot/platforms/ble?go-get=1 (status code 200)
get "gobot.io/x/gobot/platforms/ble": found meta tag main.metaImport{Prefix:"gobot.io/x/gobot", VCS:"git", RepoRoot:"https://github.com/hybridgroup/gobot"} at https://gobot.io/x/gobot/platforms/ble?go-get=1
get "gobot.io/x/gobot/platforms/ble": verifying non-authoritative meta tag
github.com/currantlabs/ble (download)
github.com/pkg/errors (download)
Fetching https://golang.org/x/net/context?go-get=1
Parsing meta tags from https://golang.org/x/net/context?go-get=1 (status code 200)
get "golang.org/x/net/context": found meta tag main.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/context?go-get=1
get "golang.org/x/net/context": verifying non-authoritative meta tag
Fetching https://golang.org/x/net?go-get=1
Parsing meta tags from https://golang.org/x/net?go-get=1 (status code 200)
golang.org/x/net (download)
Fetching https://gobot.io/x/gobot/platforms/chip?go-get=1
Parsing meta tags from https://gobot.io/x/gobot/platforms/chip?go-get=1 (status code 200)
get "gobot.io/x/gobot/platforms/chip": found meta tag main.metaImport{Prefix:"gobot.io/x/gobot", VCS:"git", RepoRoot:"https://github.com/hybridgroup/gobot"} at https://gobot.io/x/gobot/platforms/chip?go-get=1
get "gobot.io/x/gobot/platforms/chip": verifying non-authoritative meta tag
Fetching https://gobot.io/x/gobot/platforms/digispark?go-get=1
Parsing meta tags from https://gobot.io/x/gobot/platforms/digispark?go-get=1 (status code 200)
get "gobot.io/x/gobot/platforms/digispark": found meta tag main.metaImport{Prefix:"gobot.io/x/gobot", VCS:"git", RepoRoot:"https://github.com/hybridgroup/gobot"} at https://gobot.io/x/gobot/platforms/digispark?go-get=1
get "gobot.io/x/gobot/platforms/digispark": verifying non-authoritative meta tag
Fetching https://gobot.io/x/gobot/platforms/dragonboard?go-get=1
Parsing meta tags from https://gobot.io/x/gobot/platforms/dragonboard?go-get=1 (status code 200)
get "gobot.io/x/gobot/platforms/dragonboard": found meta tag main.metaImport{Prefix:"gobot.io/x/gobot", VCS:"git", RepoRoot:"https://github.com/hybridgroup/gobot"} at https://gobot.io/x/gobot/platforms/dragonboard?go-get=1
get "gobot.io/x/gobot/platforms/dragonboard": verifying non-authoritative meta tag
Fetching https://gobot.io/x/gobot/platforms/firmata?go-get=1
Parsing meta tags from https://gobot.io/x/gobot/platforms/firmata?go-get=1 (status code 200)
get "gobot.io/x/gobot/platforms/firmata": found meta tag main.metaImport{Prefix:"gobot.io/x/gobot", VCS:"git", RepoRoot:"https://github.com/hybridgroup/gobot"} at https://gobot.io/x/gobot/platforms/firmata?go-get=1
get "gobot.io/x/gobot/platforms/firmata": verifying non-authoritative meta tag
Fetching https://go.bug.st/serial.v1?go-get=1
Parsing meta tags from https://go.bug.st/serial.v1?go-get=1 (status code 200)
get "go.bug.st/serial.v1": found meta tag main.metaImport{Prefix:"go.bug.st/serial.v1", VCS:"git", RepoRoot:"https://go.bug.st/git/serial.v1.git"} at https://go.bug.st/serial.v1?go-get=1
go.bug.st/serial.v1 (download)
Fetching https://golang.org/x/sys/windows?go-get=1
Parsing meta tags from https://golang.org/x/sys/windows?go-get=1 (status code 200)
get "golang.org/x/sys/windows": found meta tag main.metaImport{Prefix:"golang.org/x/sys", VCS:"git", RepoRoot:"https://go.googlesource.com/sys"} at https://golang.org/x/sys/windows?go-get=1
get "golang.org/x/sys/windows": verifying non-authoritative meta tag
Fetching https://golang.org/x/sys?go-get=1
Parsing meta tags from https://golang.org/x/sys?go-get=1 (status code 200)
golang.org/x/sys (download)
Fetching https://gobot.io/x/gobot/platforms/firmata/client?go-get=1
Parsing meta tags from https://gobot.io/x/gobot/platforms/firmata/client?go-get=1 (status code 200)
get "gobot.io/x/gobot/platforms/firmata/client": found meta tag main.metaImport{Prefix:"gobot.io/x/gobot", VCS:"git", RepoRoot:"https://github.com/hybridgroup/gobot"} at https://gobot.io/x/gobot/platforms/firmata/client?go-get=1
get "gobot.io/x/gobot/platforms/firmata/client": verifying non-authoritative meta tag
Fetching https://gobot.io/x/gobot/platforms/intel-iot?go-get=1
Parsing meta tags from https://gobot.io/x/gobot/platforms/intel-iot?go-get=1 (status code 200)
get "gobot.io/x/gobot/platforms/intel-iot": found meta tag main.metaImport{Prefix:"gobot.io/x/gobot", VCS:"git", RepoRoot:"https://github.com/hybridgroup/gobot"} at https://gobot.io/x/gobot/platforms/intel-iot?go-get=1
get "gobot.io/x/gobot/platforms/intel-iot": verifying non-authoritative meta tag
Fetching https://gobot.io/x/gobot/platforms/intel-iot/curie?go-get=1
Parsing meta tags from https://gobot.io/x/gobot/platforms/intel-iot/curie?go-get=1 (status code 200)
get "gobot.io/x/gobot/platforms/intel-iot/curie": found meta tag main.metaImport{Prefix:"gobot.io/x/gobot", VCS:"git", RepoRoot:"https://github.com/hybridgroup/gobot"} at https://gobot.io/x/gobot/platforms/intel-iot/curie?go-get=1
get "gobot.io/x/gobot/platforms/intel-iot/curie": verifying non-authoritative meta tag
Fetching https://gobot.io/x/gobot/platforms/intel-iot/edison?go-get=1
Parsing meta tags from https://gobot.io/x/gobot/platforms/intel-iot/edison?go-get=1 (status code 200)
get "gobot.io/x/gobot/platforms/intel-iot/edison": found meta tag main.metaImport{Prefix:"gobot.io/x/gobot", VCS:"git", RepoRoot:"https://github.com/hybridgroup/gobot"} at https://gobot.io/x/gobot/platforms/intel-iot/edison?go-get=1
get "gobot.io/x/gobot/platforms/intel-iot/edison": verifying non-authoritative meta tag
Fetching https://gobot.io/x/gobot/platforms/intel-iot/joule?go-get=1
Parsing meta tags from https://gobot.io/x/gobot/platforms/intel-iot/joule?go-get=1 (status code 200)
get "gobot.io/x/gobot/platforms/intel-iot/joule": found meta tag main.metaImport{Prefix:"gobot.io/x/gobot", VCS:"git", RepoRoot:"https://github.com/hybridgroup/gobot"} at https://gobot.io/x/gobot/platforms/intel-iot/joule?go-get=1
get "gobot.io/x/gobot/platforms/intel-iot/joule": verifying non-authoritative meta tag
Fetching https://gobot.io/x/gobot/platforms/joystick?go-get=1
Parsing meta tags from https://gobot.io/x/gobot/platforms/joystick?go-get=1 (status code 200)
get "gobot.io/x/gobot/platforms/joystick": found meta tag main.metaImport{Prefix:"gobot.io/x/gobot", VCS:"git", RepoRoot:"https://github.com/hybridgroup/gobot"} at https://gobot.io/x/gobot/platforms/joystick?go-get=1
get "gobot.io/x/gobot/platforms/joystick": verifying non-authoritative meta tag
github.com/veandco/go-sdl2 (download)
Fetching https://gobot.io/x/gobot/platforms/keyboard?go-get=1
Parsing meta tags from https://gobot.io/x/gobot/platforms/keyboard?go-get=1 (status code 200)
get "gobot.io/x/gobot/platforms/keyboard": found meta tag main.metaImport{Prefix:"gobot.io/x/gobot", VCS:"git", RepoRoot:"https://github.com/hybridgroup/gobot"} at https://gobot.io/x/gobot/platforms/keyboard?go-get=1
get "gobot.io/x/gobot/platforms/keyboard": verifying non-authoritative meta tag
Fetching https://gobot.io/x/gobot/platforms/leap?go-get=1
Parsing meta tags from https://gobot.io/x/gobot/platforms/leap?go-get=1 (status code 200)
get "gobot.io/x/gobot/platforms/leap": found meta tag main.metaImport{Prefix:"gobot.io/x/gobot", VCS:"git", RepoRoot:"https://github.com/hybridgroup/gobot"} at https://gobot.io/x/gobot/platforms/leap?go-get=1
get "gobot.io/x/gobot/platforms/leap": verifying non-authoritative meta tag
Fetching https://golang.org/x/net/websocket?go-get=1
Parsing meta tags from https://golang.org/x/net/websocket?go-get=1 (status code 200)
get "golang.org/x/net/websocket": found meta tag main.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/websocket?go-get=1
get "golang.org/x/net/websocket": verifying non-authoritative meta tag
Fetching https://gobot.io/x/gobot/platforms/mavlink?go-get=1
Parsing meta tags from https://gobot.io/x/gobot/platforms/mavlink?go-get=1 (status code 200)
get "gobot.io/x/gobot/platforms/mavlink": found meta tag main.metaImport{Prefix:"gobot.io/x/gobot", VCS:"git", RepoRoot:"https://github.com/hybridgroup/gobot"} at https://gobot.io/x/gobot/platforms/mavlink?go-get=1
get "gobot.io/x/gobot/platforms/mavlink": verifying non-authoritative meta tag
Fetching https://gobot.io/x/gobot/platforms/mavlink/common?go-get=1
Parsing meta tags from https://gobot.io/x/gobot/platforms/mavlink/common?go-get=1 (status code 404)
Fetching https://gobot.io/x/gobot/platforms/megapi?go-get=1
Parsing meta tags from https://gobot.io/x/gobot/platforms/megapi?go-get=1 (status code 200)
get "gobot.io/x/gobot/platforms/megapi": found meta tag main.metaImport{Prefix:"gobot.io/x/gobot", VCS:"git", RepoRoot:"https://github.com/hybridgroup/gobot"} at https://gobot.io/x/gobot/platforms/megapi?go-get=1
get "gobot.io/x/gobot/platforms/megapi": verifying non-authoritative meta tag
Fetching https://gobot.io/x/gobot/platforms/microbit?go-get=1
Parsing meta tags from https://gobot.io/x/gobot/platforms/microbit?go-get=1 (status code 200)
get "gobot.io/x/gobot/platforms/microbit": found meta tag main.metaImport{Prefix:"gobot.io/x/gobot", VCS:"git", RepoRoot:"https://github.com/hybridgroup/gobot"} at https://gobot.io/x/gobot/platforms/microbit?go-get=1
get "gobot.io/x/gobot/platforms/microbit": verifying non-authoritative meta tag
Fetching https://gobot.io/x/gobot/platforms/mqtt?go-get=1
Parsing meta tags from https://gobot.io/x/gobot/platforms/mqtt?go-get=1 (status code 200)
get "gobot.io/x/gobot/platforms/mqtt": found meta tag main.metaImport{Prefix:"gobot.io/x/gobot", VCS:"git", RepoRoot:"https://github.com/hybridgroup/gobot"} at https://gobot.io/x/gobot/platforms/mqtt?go-get=1
get "gobot.io/x/gobot/platforms/mqtt": verifying non-authoritative meta tag
github.com/eclipse/paho.mqtt.golang (download)
Fetching https://golang.org/x/net/proxy?go-get=1
Parsing meta tags from https://golang.org/x/net/proxy?go-get=1 (status code 200)
get "golang.org/x/net/proxy": found meta tag main.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/proxy?go-get=1
get "golang.org/x/net/proxy": verifying non-authoritative meta tag
Fetching https://gobot.io/x/gobot/platforms/nats?go-get=1
Parsing meta tags from https://gobot.io/x/gobot/platforms/nats?go-get=1 (status code 200)
get "gobot.io/x/gobot/platforms/nats": found meta tag main.metaImport{Prefix:"gobot.io/x/gobot", VCS:"git", RepoRoot:"https://github.com/hybridgroup/gobot"} at https://gobot.io/x/gobot/platforms/nats?go-get=1
get "gobot.io/x/gobot/platforms/nats": verifying non-authoritative meta tag
github.com/nats-io/nats (download)
github.com/nats-io/go-nats (download)
github.com/nats-io/nuid (download)
Fetching https://gobot.io/x/gobot/platforms/neurosky?go-get=1
Parsing meta tags from https://gobot.io/x/gobot/platforms/neurosky?go-get=1 (status code 200)
get "gobot.io/x/gobot/platforms/neurosky": found meta tag main.metaImport{Prefix:"gobot.io/x/gobot", VCS:"git", RepoRoot:"https://github.com/hybridgroup/gobot"} at https://gobot.io/x/gobot/platforms/neurosky?go-get=1
get "gobot.io/x/gobot/platforms/neurosky": verifying non-authoritative meta tag
Fetching https://gobot.io/x/gobot/platforms/opencv?go-get=1
Parsing meta tags from https://gobot.io/x/gobot/platforms/opencv?go-get=1 (status code 200)
get "gobot.io/x/gobot/platforms/opencv": found meta tag main.metaImport{Prefix:"gobot.io/x/gobot", VCS:"git", RepoRoot:"https://github.com/hybridgroup/gobot"} at https://gobot.io/x/gobot/platforms/opencv?go-get=1
get "gobot.io/x/gobot/platforms/opencv": verifying non-authoritative meta tag
github.com/lazywei/go-opencv (download)
Fetching https://gobot.io/x/gobot/platforms/parrot?go-get=1
Parsing meta tags from https://gobot.io/x/gobot/platforms/parrot?go-get=1 (status code 200)
get "gobot.io/x/gobot/platforms/parrot": found meta tag main.metaImport{Prefix:"gobot.io/x/gobot", VCS:"git", RepoRoot:"https://github.com/hybridgroup/gobot"} at https://gobot.io/x/gobot/platforms/parrot?go-get=1
get "gobot.io/x/gobot/platforms/parrot": verifying non-authoritative meta tag
Fetching https://gobot.io/x/gobot/platforms/parrot/ardrone?go-get=1
Parsing meta tags from https://gobot.io/x/gobot/platforms/parrot/ardrone?go-get=1 (status code 200)
get "gobot.io/x/gobot/platforms/parrot/ardrone": found meta tag main.metaImport{Prefix:"gobot.io/x/gobot", VCS:"git", RepoRoot:"https://github.com/hybridgroup/gobot"} at https://gobot.io/x/gobot/platforms/parrot/ardrone?go-get=1
get "gobot.io/x/gobot/platforms/parrot/ardrone": verifying non-authoritative meta tag
github.com/hybridgroup/go-ardrone (download)
Fetching https://gobot.io/x/gobot/platforms/parrot/bebop?go-get=1
Parsing meta tags from https://gobot.io/x/gobot/platforms/parrot/bebop?go-get=1 (status code 200)
get "gobot.io/x/gobot/platforms/parrot/bebop": found meta tag main.metaImport{Prefix:"gobot.io/x/gobot", VCS:"git", RepoRoot:"https://github.com/hybridgroup/gobot"} at https://gobot.io/x/gobot/platforms/parrot/bebop?go-get=1
get "gobot.io/x/gobot/platforms/parrot/bebop": verifying non-authoritative meta tag
Fetching https://gobot.io/x/gobot/platforms/parrot/bebop/client?go-get=1
Parsing meta tags from https://gobot.io/x/gobot/platforms/parrot/bebop/client?go-get=1 (status code 404)
Fetching https://gobot.io/x/gobot/platforms/parrot/minidrone?go-get=1
Parsing meta tags from https://gobot.io/x/gobot/platforms/parrot/minidrone?go-get=1 (status code 200)
get "gobot.io/x/gobot/platforms/parrot/minidrone": found meta tag main.metaImport{Prefix:"gobot.io/x/gobot", VCS:"git", RepoRoot:"https://github.com/hybridgroup/gobot"} at https://gobot.io/x/gobot/platforms/parrot/minidrone?go-get=1
get "gobot.io/x/gobot/platforms/parrot/minidrone": verifying non-authoritative meta tag
Fetching https://gobot.io/x/gobot/platforms/particle?go-get=1
Parsing meta tags from https://gobot.io/x/gobot/platforms/particle?go-get=1 (status code 200)
get "gobot.io/x/gobot/platforms/particle": found meta tag main.metaImport{Prefix:"gobot.io/x/gobot", VCS:"git", RepoRoot:"https://github.com/hybridgroup/gobot"} at https://gobot.io/x/gobot/platforms/particle?go-get=1
get "gobot.io/x/gobot/platforms/particle": verifying non-authoritative meta tag
github.com/donovanhide/eventsource (download)
Fetching https://gobot.io/x/gobot/platforms/pebble?go-get=1
Parsing meta tags from https://gobot.io/x/gobot/platforms/pebble?go-get=1 (status code 200)
get "gobot.io/x/gobot/platforms/pebble": found meta tag main.metaImport{Prefix:"gobot.io/x/gobot", VCS:"git", RepoRoot:"https://github.com/hybridgroup/gobot"} at https://gobot.io/x/gobot/platforms/pebble?go-get=1
get "gobot.io/x/gobot/platforms/pebble": verifying non-authoritative meta tag
Fetching https://gobot.io/x/gobot/platforms/sphero?go-get=1
Parsing meta tags from https://gobot.io/x/gobot/platforms/sphero?go-get=1 (status code 200)
get "gobot.io/x/gobot/platforms/sphero": found meta tag main.metaImport{Prefix:"gobot.io/x/gobot", VCS:"git", RepoRoot:"https://github.com/hybridgroup/gobot"} at https://gobot.io/x/gobot/platforms/sphero?go-get=1
get "gobot.io/x/gobot/platforms/sphero": verifying non-authoritative meta tag
Fetching https://gobot.io/x/gobot/platforms/sphero/bb8?go-get=1
Parsing meta tags from https://gobot.io/x/gobot/platforms/sphero/bb8?go-get=1 (status code 200)
get "gobot.io/x/gobot/platforms/sphero/bb8": found meta tag main.metaImport{Prefix:"gobot.io/x/gobot", VCS:"git", RepoRoot:"https://github.com/hybridgroup/gobot"} at https://gobot.io/x/gobot/platforms/sphero/bb8?go-get=1
get "gobot.io/x/gobot/platforms/sphero/bb8": verifying non-authoritative meta tag
Fetching https://gobot.io/x/gobot/platforms/sphero/ollie?go-get=1
Parsing meta tags from https://gobot.io/x/gobot/platforms/sphero/ollie?go-get=1 (status code 200)
get "gobot.io/x/gobot/platforms/sphero/ollie": found meta tag main.metaImport{Prefix:"gobot.io/x/gobot", VCS:"git", RepoRoot:"https://github.com/hybridgroup/gobot"} at https://gobot.io/x/gobot/platforms/sphero/ollie?go-get=1
get "gobot.io/x/gobot/platforms/sphero/ollie": verifying non-authoritative meta tag
Fetching https://gobot.io/x/gobot/platforms/tinkerboard?go-get=1
Parsing meta tags from https://gobot.io/x/gobot/platforms/tinkerboard?go-get=1 (status code 200)
get "gobot.io/x/gobot/platforms/tinkerboard": found meta tag main.metaImport{Prefix:"gobot.io/x/gobot", VCS:"git", RepoRoot:"https://github.com/hybridgroup/gobot"} at https://gobot.io/x/gobot/platforms/tinkerboard?go-get=1
get "gobot.io/x/gobot/platforms/tinkerboard": verifying non-authoritative meta tag
