### ISSUE TITLE
An example to convert i2c drivers written in C/C++ and Python to golang

### ISSUE THREAD

**Issue by chaitanya9186** [hybridgroup/gobot#436]
Hi

I would like to work on #435 (Implement LSM9DS0 device driver). 

I have [reference code](https://github.com/adafruit/Adafruit_LSM9DS0_Library) available in C++. Is there anyway I can convert this straight into gobot i2c device driver. 

Please provide me if there are any examples.

Thank you.

**Comment by deadprogram** [comment]
Although it is possible to wrap C/C++ code in Golang, all of our i2c drivers, and most of the code that we can, is written in pure Golang to make it easier to cross-compile, and reduce dependencies.

We would normally just examine the C++ reference code, and "manually transpile" it into Golang. It would be ideal if we had some docs on this, or someone wrote a blog post.

**Comment by gen2thomas** [comment]
I'm going to close this issue, because there are programs available, which can transform code to golang. Also enough documentation is out there, so we do not reinvent the wheel here.
