### ISSUE TITLE
raspberry pi built-in pull up/down resistor support?

### ISSUE THREAD

**Issue by boundedinfinity** [hybridgroup/gobot#439]
Is there a way to configure the raspberry pi internal pull up/down resistors?  I'm looking for help (or just a pointer to documentation) do some something similar to the configuration of the GPIO pin's pull up/down resistor in the python [RPi.GPIO](https://sourceforge.net/p/raspberry-gpio-python/wiki/BasicUsage/) module.

In python the configuration is achieved by something like this:

```python
GPIO.setup(PIN, GPIO.IN, pull_up_down = GPIO.PUD_DOWN)
```

Does gobot have something similar?

**Comment by spatil** [comment]
Is there any workaround for this?

**Comment by gokuu** [comment]
I have the same issue :(

**Comment by stuartleeks** [comment]
@deadprogram - do you have any sense of what would be needed to add this? (From what I can tell it isn't currently supported?)

**Comment by gen2thomas** [comment]
part of release v2.0.0
