### ISSUE TITLE
ssd1306_driver

### ISSUE THREAD

**Issue by qarth** [hybridgroup/gobot#446]
How do you display text with the ssd1306_driver driver?

**Comment by deadprogram** [comment]
Hi @qarth right now the functionality is rather limited. 

Once a SPI interface has landed into Gobot dev, a more performant interface to the SSD1306 will be possible, and drawing text a more reasonable prospect.

**Comment by deadprogram** [comment]
I think that @ulisesflynn is going to work on the SPI version of this driver in the near future. :smile_cat:

**Comment by ulisesflynn** [comment]
I've been pretty busy this past week, but I'll get to this soon!

**Comment by mikegleasonjr** [comment]
Here's an example displaying the current time:

```
package main

import (
	"image"
	"time"

	"github.com/fogleman/gg"
	"gobot.io/x/gobot"
	"gobot.io/x/gobot/drivers/i2c"
	"gobot.io/x/gobot/platforms/raspi"
)

func main() {
	r := raspi.NewAdaptor()
	d := i2c.NewSSD1306Driver(r)

	work := func() {
		d.Clear()
		d.Display()

		ctx := gg.NewContext(d.Buffer.Width, d.Buffer.Height)

		gobot.Every(time.Second, func() {
			ctx.SetRGB(0, 0, 0)
			ctx.Clear()
			ctx.SetRGB(1, 1, 1)
			ctx.DrawStringAnchored(time.Now().Format("15:04:05"), 0, 0, 0, 1)
			transfer(d, ctx.Image())
		})
	}

	robot := gobot.NewRobot("blinkBot",
		[]gobot.Connection{r},
		[]gobot.Device{d},
		work,
	)

	robot.Start()
}

func transfer(d *i2c.SSD1306Driver, img image.Image) {
	d.Clear()
	for y, w, h := 0, img.Bounds().Dx(), img.Bounds().Dy(); y < h; y++ {
		for x := 0; x < w; x++ {
			c := img.At(x, y)
			r, _, _, _ := c.RGBA()
			if r == 0 {
				continue
			}
			d.Set(x, y, 1)
		}
	}
	d.Display()
}
```
Basically I render an image in memory using a 3rd party library, then I set the pixels one by one of that image on the ssd1306.

**Comment by deadprogram** [comment]
Hi @mikegleasonjr that transfer looks useful. Perhaps a version of that function `TransferImage` could be added to the driver itself? I'd gladly accept such a PR.

**Comment by mikegleasonjr** [comment]
@deadprogram Great, will happily do!

**Comment by deadprogram** [comment]
Hi @mikegleasonjr any chance of still getting this PR? :smile_cat:

**Comment by deadprogram** [comment]
Now closing this issue since ssd1306 support is in fact in Gobot. Still love to see a PR with the image transfer feature.
