### ISSUE TITLE
Use dep for dependency management

### ISSUE THREAD

**Issue by trevrosen** [hybridgroup/gobot#454]
## What
I'm proposing to use [dep](https://github.com/golang/dep) as a tool to ensure a canonical dependency installation process for development.

## Why
It will make development far smoother and make reproducible builds much easier.

## Caveat
The `dep` tool requires Go 1.8 or higher. I believe that this is acceptable given that the Go team has committed to making this **the** tool for managing dependencies in Go software projects, but I admit I'm not fully aware of what concerns drive Gobot using 1.7 as the minimal supported version.

**Comment by deadprogram** [comment]
Hi @trevrosen this seems like a great idea to me.

**Comment by deadprogram** [comment]
Hello @trevrosen regarding your question about what has been driving the backward version compatibility. We have been trying to ensure support for the current version of Go - 2, but perhaps we should instead mimic the Go languages's own policy: https://golang.org/doc/devel/release.html#policy

**Comment by deadprogram** [comment]
This thread describes some specific issues regarding Go language compat. and Gobot: https://github.com/hybridgroup/gobot/issues/390#issuecomment-289812820

**Comment by deadprogram** [comment]
Thanks to @trevrosen this is now in the `dev` branch. I will close this issue once it makes it into the next release.
