### ISSUE TITLE
Esp32 Dual Core 

### ISSUE THREAD

**Issue by monouser7dig** [hybridgroup/gobot#485]
I‘d like to utilise the two cores of the esp32.
Is there any way to do this using go routines?

Thanks

**Comment by deadprogram** [comment]
Hi @monouser7dig it is not yet possible to compile/run Go on any RTOS. I look forward to this capability someday!

**Comment by monouser7dig** [comment]
I was thinking using gobot alone without an RTOS?
As far as I read gobot should be able to compile code for the esp32, only question is if some sort of concurrency can be used (easily). 

Or do you mean, using the two cores is not possible without an RTOS?
Is it possible to target each core using gobot so one could work on that?

**Comment by deadprogram** [comment]
To clarify, there is not currently any way to execute Go code directly on any microcontrollers. The typical pattern for using microcontrollers from Gobot has been to run Go code on an embedded Linux, and communicate with a microcontroller using serial/wifi/bluetooth/i2c.

**Comment by monouser7dig** [comment]
ok sorry, misunderstood, thought it was something along the lines of [micropython](https://micropython.org) providing a subset of go for micrcontrollers.

> Go on any RTOS. I look forward to this capability someday!

yes

**Comment by deadprogram** [comment]
The llvm go compiler work can be found at http://llvm.org/viewvc/llvm-project/llvm/trunk/bindings/go/

Also check out this interesting project from @lpereira called Gomoku https://github.com/lpereira/gomoku

Lastly, this work also looks interesting: https://github.com/ycoroneos/G.E.R.T
