### ISSUE TITLE
sphero ollie: add "SetHeading" command to driver not working

### ISSUE THREAD

**Issue by PrasadG193** [hybridgroup/gobot#486]
Hi,
In our application, we want to change heading of the ollie bot on particular event. As set heading command is missing from gobot ollie-driver, we are trying to add support of it with the help of https://s3.amazonaws.com/docs.gosphero.com/api/Sphero_API_1.20.pdf. In API doc, command structure of set heading is given as,

DID | CID  |  SEQ  |  DLEN  |  HEADING
02h | 01h  |  \<any\> |   03h    |  16-bit value

In the packet structure of ollie-driver, every field is treated as a byte. I see the command in implemented in sphero-driver, but the same implementation doesn't work for ollie-driver(i.e. splitting HEADING field into MSB and LSB while crafting packet). Can anyone suggest me, how to implement this?

**Comment by deadprogram** [comment]
Hello, @PrasadG193 I would expect the implementation to be similar to https://github.com/hybridgroup/gobot/blob/master/platforms/sphero/ollie/ollie_driver.go#L194

Hopefully that is helpful as a point of reference.

**Comment by PrasadG193** [comment]
@deadprogram I have already tried that approach but it didn't work. If you see structure of Roll command in API reference doc, 

DID | CID | SEQ | DLEN | Speed | Heading | Heading | STATE
02h | 30h | \<any\>| 05h | \<val\> | \<msb\> | \<lsb\> | \<bool\>

which is different than that of Set Heading command. In Roll command heading is split into MSB and LSB. But in Set Heading, 16-bit heading parameter is passed as it is.

**Comment by deadprogram** [comment]
I would expect that something like this should work:

```
s.packetChannel <- s.craftPacket([]uint8{uint8(heading >> 8), uint8(heading & 0xFF)}, 0x02, 0x01)
```

**Comment by deadprogram** [comment]
See https://github.com/hybridgroup/gobot/blob/master/platforms/sphero/sphero_driver.go#L275

**Comment by PrasadG193** [comment]
I have tried that. Didn't work for Ollie bot. I am not sure if it even works for sphero bot also.

**Comment by deadprogram** [comment]
I think that function does not operate the way you think it does? Not 100% sure on that but as I vaguely recall it is very odd behavior.

**Comment by gen2thomas** [comment]
Hi @PrasadG193 is this still an open issue?

**Comment by gen2thomas** [comment]
I'm going to close this issue because it seems it is out of interest now. Feel free to reopen it or create a new issue for this topic.
