### ISSUE TITLE
Is I2C goroutine thread safe?

### ISSUE THREAD

**Issue by FerventGeek** [hybridgroup/gobot#488]
If I have a number of goroutines writing to the I2C bus via i2c.PCA9685Driver, is `gobot.io/x/gobot/drivers/i2c` protecting the I2C bus from simultaneous sends, or should I monitor a channel and set up a dispatcher queue? Thx for this amazing project!

update: Or, I could look at the code, duh.  This looks locked during write, true?

```golang
func (c *i2cConnection) Write(data []byte) (written int, err error) {
	c.mutex.Lock()
        defer c.mutex.Unlock()
        ...
```

**Comment by deadprogram** [comment]
Hi @FerventGeek you found the answer, that mutex is there to protect concurrent access to a bus/address aka `i2cConnection`.
