### ISSUE TITLE
Can't install gobot package

### ISSUE THREAD

**Issue by GreenFantomas** [hybridgroup/gobot#512]
When I try to `go get -d -u gobot.io/x/gobot/...`, I have this error:
```
package gocv.io/x/gocv: unrecognized import path "gocv.io/x/gocv" (https fetch: Get https://gocv.io/x/gocv?go-get=1: dial tcp 104.31.69.205:443: i/o timeout)
```
How to fix it?

**Comment by deadprogram** [comment]
Hello @GreenFantomas I am not able to reproduce your problem on a clean Go install using Go 1.9.5.

```
$ gvm use go1.9.5
Now using version go1.9.5
$ go get -d -u gobot.io/x/gobot/...
```

What OS and Go version are you using?

**Comment by GreenFantomas** [comment]
I use Go 1.10.1 on linux/amd64.

**Comment by GreenFantomas** [comment]
I use ArchLinux(4.15.15-1-ARCH).

**Comment by jadr2ddude** [comment]
I have the exact same go version and OS and this works fine. Also btw we have go1.10.1 in travis. . . which works.

**Comment by GreenFantomas** [comment]
@jadr2ddude, yes you are right. My provider blocked gocv.io, and I just cloned the gocv project from github and compiled it. Now it works! Thanks to everyone for replies!
