### ISSUE TITLE
Tello and video on Windows 10 does not start

### ISSUE THREAD

**Issue by fabriziomarini** [hybridgroup/gobot#515]
I'm using gobot with tello and it is ok .... but if i try tello_video.go with Mplayer installed on Windows 10 I only see in the output:
2018/04/29 18:24:43 Initializing connections...
2018/04/29 18:24:43 Initializing devices...
2018/04/29 18:24:43 Initializing device Tello-6DD8127A03A3B7AB ...
2018/04/29 18:24:43 Robot tello initialized.
2018/04/29 18:24:43 Starting Robot tello ...
2018/04/29 18:24:43 Starting connections...
2018/04/29 18:24:43 Starting devices...
2018/04/29 18:24:43 Starting device Tello-6DD8127A03A3B7AB...
2018/04/29 18:24:43 Starting work...

No video start ... tello it is connected

**Comment by deadprogram** [comment]
Hi @fabriziomarini just wondering if you need to change the line https://github.com/hybridgroup/gobot/blob/master/examples/tello_video.go#L29 to use `"mplayer.exe"` as the first param to the `exec.Command()` function due to running on Windows. Please give that a try, and let me know.

**Comment by fabriziomarini** [comment]
I have tried but nothing change.
I have also used a cmd as administrator to start the "go run ...."
My dubt is that I do no see "Connected" on the console the one used in line https://github.com/hybridgroup/gobot/blob/master/examples/tello_video.go#L37

**Comment by deadprogram** [comment]
Are you able to run the example `tello.go`?

**Comment by fabriziomarini** [comment]
Yes tello.go work fine.

**Comment by deadprogram** [comment]
What version of Windows are you using? Also, is mplayer.exe in your `PATH`?

**Comment by deadprogram** [comment]
Also, I wonder if https://www.reddit.com/r/golang/comments/8e9las/problem_using_readfromudp_on_windows_to_discover/ might be related?

**Comment by fabriziomarini** [comment]
OS Name	Microsoft Windows 10 Pro
Version	10.0.15063 Build 15063
Yes mplayer it is in the path

**Comment by gen2thomas** [comment]
Hi @fabriziomarini and @deadprogram , because there seems to be no related issue since 2018 for MS Windows, my suggestion is to close this issue.

**Comment by deadprogram** [comment]
Agreed. Thanks everyone!
