### ISSUE TITLE
Do we must run dep ensure before contribunting?

### ISSUE THREAD

**Issue by morfeo8marc** [hybridgroup/gobot#524]
Hi,
I wanted to contribute #523 but had an old version of github.com/veandco/go-sdl2. That's the reason why I created https://github.com/hybridgroup/gobot/pull/523/commits/0fd6cf480a6b08649a4691585d7b0fbc8e16ed5e commit.
After noticing the mismatch of dependencies, I've notice that _go dep_ to vendor dependencies was used.
This is my first time contributing to gobot, and to avoid mistakes to other new comers, should we improve the contributing guide and mention that **dep ensure** must be executed before?

**Comment by trevrosen** [comment]
Addressed by #526  -- thanks for the contribution!
