### ISSUE TITLE
Tello Driver: Why are the FlightData fields not exported?

### ISSUE THREAD

**Issue by SMerrony** [hybridgroup/gobot#531]
Am I missing something, or is there a reason the fields of the FlightData struct are not exported?

**Comment by deadprogram** [comment]
Hi @SMerrony that was strictly an oversight. We'd be grateful for a PR that exported all of them!

**Comment by SMerrony** [comment]
PR #532 submitted :-)

**Comment by deadprogram** [comment]
Thanks!

**Comment by deadprogram** [comment]
Version 1.11.0 has just been released that includes this. Now closing, thank you @SMerrony
