### ISSUE TITLE
Tello Driver: Change some FlightData fields to bool type

### ISSUE THREAD

**Issue by SMerrony** [hybridgroup/gobot#533]
It seems to me that many of the fields in the FlightData struct can contain int16 values of either 0 or 1.  Eg. all the fields extracted in ParseFlightData with an ``& 0x1``

Would it not be much more idiomatic to represent these as bool values in Go?

Happy to make this change if you think it worthwhile.

**Comment by deadprogram** [comment]
Seems like a good idea to me!

**Comment by deadprogram** [comment]
Version 1.11.0 has just been released that includes this. Now closing, thanks @SMerrony !
