### ISSUE TITLE
Tello Driver: Support for more modes.

### ISSUE THREAD

**Issue by cbwang2016** [hybridgroup/gobot#536]
Such as Bounce Mode, Throw & Go

**Comment by cbwang2016** [comment]
@deadprogram Do you have the protocol information for these modes?

**Comment by deadprogram** [comment]
@cbwang2016 you should try to combine efforts with @SMerrony who also is working on this.

**Comment by cbwang2016** [comment]
@deadprogram Yes. And personally I think you should release a new version now for all those minor bug fixes for tello.
