### ISSUE TITLE
golint cleanup

### ISSUE THREAD

**Issue by niaow** [hybridgroup/gobot#544]
I have been looking through the code, and my IDE keeps finding golint issues. I would like to fix these issues.

**Comment by jadr2ddude** [comment]
@deadprogram  should [this](https://github.com/hybridgroup/gobot/blob/6fb9c3991b5d9225e71c0e46b4239da33395251a/drivers/i2c/jhd1313m1_driver.go#L11) be JHD1313M1_REG_RED? It does not currently follow the convention you have been using.

**Comment by deadprogram** [comment]
Probably so, yes @jadr2ddude

**Comment by jadr2ddude** [comment]
I am currently busy at the moment. I will hopefully have this ready for the next release cycle.

**Comment by gen2thomas** [comment]
I will try to add some more linters to golangci-lint and fix the related issues. Maybe starting with "gofmt" is a good idea.
