### ISSUE TITLE
Bitshift past the end of a byte (gopigo3)

### ISSUE THREAD

**Issue by jadr2ddude** [hybridgroup/gobot#546]
https://github.com/hybridgroup/gobot/blob/108cfecd02fa6904b91983064647af2b0dd3543d/platforms/dexter/gopigo3/driver.go#L491

The first part does a 8 left bitshift on an 8-bit type.

**Comment by jadr2ddude** [comment]
I currenly have a lack of knowledge of what the first code is supposed to do. Does anyone here understand what these were supposed to do? If you can explain it or link relevant docs, I can fix it.

**Comment by deadprogram** [comment]
Thanks @ulisesflynn

**Comment by deadprogram** [comment]
This has been released as part of v1.11.1 so closing. Thank you to everyone.
