### ISSUE TITLE
throttle unused in Tello driver?

### ISSUE THREAD

**Issue by cbwang2016** [hybridgroup/gobot#549]
I searched the word "throttle" in file https://github.com/hybridgroup/gobot/blob/dev/platforms/dji/tello/driver.go
The word appears only twice:
`rx, ry, lx, ly, throttle float32`
and
`axis5 := int16(660.0*d.throttle + 1024.0)`
There's not even a function to set this "throttle".
Is this a bug?

**Comment by deadprogram** [comment]
Hi @cbwang2016 it is really just an overlooked function. A PR that implemented would be welcomed.
