### ISSUE TITLE
[BUG] Joystick: xbox360 Controller certain button not working

### ISSUE THREAD

**Issue by imathno** [hybridgroup/gobot#553]
I have been messing around with mapping the Xbox Controller to the Tello. I have found that RT, LT, and DPAD buttons aren't being registered. I tested with multiple controllers and the problem persists.

**Comment by deadprogram** [comment]
You should try the `dev` branch @imathno

**Comment by imathno** [comment]
@deadprogram I checked out the dev branch and it seems to still be a problem.

**Comment by imathno** [comment]
I figured out a fix should I open a PR?

**Comment by deadprogram** [comment]
Yes, please and thank you.

**Comment by deadprogram** [comment]
Version 1.11.0 has just been released that includes this. Now closing, thanks everyone!
