### ISSUE TITLE
MQTT: how do I resubscribe after reconnect?

### ISSUE THREAD

**Issue by neewbee** [hybridgroup/gobot#570]

**Comment by neewbee** [comment]
```golang
// +build example
//
// Do not build by default.

package main

import (
	"fmt"
	"time"

	"gobot.io/x/gobot"
	"gobot.io/x/gobot/platforms/mqtt"
)

func main() {
	mqttAdaptor := mqtt.NewAdaptor("tcp://localhost:1883", "pinger")

	work := func() {
		mqttAdaptor.On("hello", func(msg mqtt.Message) {
			fmt.Println("hello")
		})
		mqttAdaptor.On("hola", func(msg mqtt.Message) {
			fmt.Println("hola")
		})
		data := []byte("o")
		gobot.Every(1*time.Second, func() {
			mqttAdaptor.Publish("hello", data)
		})
		gobot.Every(5*time.Second, func() {
			mqttAdaptor.Publish("hola", data)
		})
	}

	robot := gobot.NewRobot("mqttBot",
		[]gobot.Connection{mqttAdaptor},
		work,
	)

	robot.Start()
}
```
several seconds after stopping mqtt server, reconnect will happen. But Work no longer works

**Comment by deadprogram** [comment]
@trevrosen this is one of the things we want to be able to solve with your latest work in progress.

**Comment by trevrosen** [comment]
@deadprogram indeed! Speaking of which you want me to proceed to PR w/ the implementation basically as it stands? Should we talk through some implications for existing installs etc?

**Comment by grtfou** [comment]
I use two settings and it looks fine to my case. (gobot v1.12.0)
Maybe it's a solution if we're hard to monitor connection status.
```go
mqttAdaptor.SetAutoReconnect(true)
mqttAdaptor.SetCleanSession(false)
```

**Comment by trevrosen** [comment]
@neewbee sorry for my silence on this -- it fell through the cracks. There's a new construct in the `dev` branch called RobotWork which gives you some external control of the workloads a robot is using. Please have a look at that and let me know (via this thread) whether it gives you the semantics you need to help solve your issue.

**Comment by trevrosen** [comment]
Hi @neewbee I believe that [this PR](https://github.com/hybridgroup/gobot/pull/650) may also help you. I'm going to close this issue for now.
