### ISSUE TITLE
Improve error handling in joystick driver

### ISSUE THREAD

**Issue by carl-ranson** [hybridgroup/gobot#574]
There are a couple of unhanded error cases in the joysick_driver.go code

the Start method begins with a switch statement to handle a various conditions. The default case is to call loadFile(). The error that is returned from loadFile is discarded meaning an error in the config file path goes undetected. 

Secondly, within the loadFIle method, is a call to json.Unmarshal. the error returned by this is also ignored which means a structural error in the config file goes undetected

Both of these paths should generate an error events consistent with the other error handling in this file.

**Comment by gen2thomas** [comment]
The error of [json.Unmarshal](https://pkg.go.dev/encoding/json#Unmarshal) call is still [unhandled](https://github.com/hybridgroup/gobot/blob/d8081f912d324f570c6e3fa74aba7c203e53bb27/platforms/joystick/joystick_driver.go#L242).
