### ISSUE TITLE
Docs: general concepts require some explanation

### ISSUE THREAD

**Issue by krancour** [hybridgroup/gobot#613]
While there's obviously a general pattern that almost all examples seem to follow, that pattern doesn't seem to be explained well anywhere in the documentation.

A newbie is easily left with the question: What is an adaptor vs what is a driver vs what is a robot?

Understanding the role in general of each of adapter, driver, and robot would be enormously helpful.

**Comment by deadprogram** [comment]
Hello @krancour please take a look at https://gobot.io/documentation/core/robots/ and the other pages within that section.

**Comment by krancour** [comment]
This was answered to my satisfaction quite some time ago. Closing.
