### ISSUE TITLE
How would you "abstract" the readable devices?

### ISSUE THREAD

**Issue by lucavallin** [hybridgroup/gobot#625]
To reduce boilerplate, I am using something like the following:

```
	var sensors map[string]gobot.Device
	sensors["sound"] = aio.NewGroveSoundSensorDriver(gp, "A0")
	sensors["temperature"] = aio.NewGroveTemperatureSensorDriver(gp, "A1")
	sensors["light"] = aio.NewGroveLightSensorDriver(gp, "A2")

	work := func() {
		gobot.Every(timeInterval, func() {
			for name, driver := range sensors {
				val, _ := driver.Read()
				json, _:= json.Marshal(messages.NewReading(name, val))
				mqttAdaptor.Publish("from", json)
			}
		})
	}
```

This won't compile since gobot.Device does not implement a Read() method. Any idea?

**Comment by lucavallin** [comment]
I see this is tagged as enhancement, but in the meantime, do you have any suggestions about how to wrap this up? Maybe by wrapping each sensor in some object which implements an interface, and then having a big list of sensors to loop through?

**Comment by gen2thomas** [comment]
Hi @lucavallin , IMO this can be solved now by using "AnalogSensorDriver".

old: `var sensors map[string]gobot.Device`
new: `var sensors map[string]aio.AnalogSensorDriver`

Best regards Thomas

**Comment by gen2thomas** [comment]
A more generic solution (interfaces in Go at client side):
```
type MyReader interface {
	Read() (float64, error)
}

func main() {
	gp := edison.NewAdaptor()

	sensors := make(map[string]MyReader)
	sensors["sound"] = aio.NewGroveSoundSensorDriver(gp, "A0")
	sensors["temperature"] = aio.NewGroveTemperatureSensorDriver(gp, "A1")
	sensors["light"] = aio.NewGroveLightSensorDriver(gp, "A2")
...
```

**Comment by gen2thomas** [comment]
I'm going to close this issue, because this is more programming language related and do not affect gobot.
