### ISSUE TITLE
Cron helper

### ISSUE THREAD

**Issue by andrewebdev** [hybridgroup/gobot#642]
It would be nice to have a cron helper so that we can execute tasks this way.

`Every` and `After` exists and are nice, but our project requires very specific scheduling.
Currently we are using `github.com/robfig/cron` which works well for us at the moment, but a cron helper for gobot may be a nice addition so that we don't need to rely on another library? 

Not a big deal not having it, just nicer with fewer external dependencies.

**Comment by trevrosen** [comment]
Hi @andrewebdev thanks for the comment. I believe that such a helper would be outside the intended scope of Gobot, but @deadprogram might have another opinion.

If you're interested in finer-grained control, I've added an experimental "work management" system for Robots on the `dev` branch: https://github.com/hybridgroup/gobot/blob/dev/robot_work.go
