### ISSUE TITLE
can i use an autopilot with tello?

### ISSUE THREAD

**Issue by jdavidthomson** [hybridgroup/gobot#643]
can i use an autopilot with a tello?  Are there any implementations for gobot that allow to automatically maka a video of an entire apartment?  like a walkthrough?

Thanks!

**Comment by trevrosen** [comment]
I'm not aware of a good way to do this because there aren't any good way finding capabilities built into it. No GPS, no LIDAR, etc. It's basically a really really fun toy :-)
