### ISSUE TITLE
Raspi SPI seems to disconnect

### ISSUE THREAD

**Issue by schmorrison** [hybridgroup/gobot#649]
Hello,

I am using GoBot in a project that uses the Raspberry Pi and the MCP3008 driver to read analog sensors over SPI. It works nearly perfectly, however after about 5 days, sometimes as long as 20 days, the program stops reading analog values. Errors do not seem to be returned in the calls to the MCP3008 device. But I do get a SPI device already disconnected error when shutting down the program after the problem occurs.

I am not very familiar with the Debian SPI device so debugging this problem is a bit beyond me. Any help would be appreciated.

Thanks and happy new year.

**Comment by trevrosen** [comment]
@schmorrison thanks for your interest in Gobot, and apologies for getting back late on this. Unfortunately we don't have the bandwidth to help folks debug their individual devices over GitHub. You can always reach out on Gopher Slack in #gobot and frequently there's someone there who'll have some insights.
