### ISSUE TITLE
Receiving video from Tello sdk (java)

### ISSUE THREAD

**Issue by lowieslach** [hybridgroup/gobot#656]
When I read the documentation, the 2 first bytes of the data of the UDPpacket  with the video data, contains a index and sub-index. But when I check this, it looks something different.
The documentation that I'm usings is: https://gobot.io/blog/2018/04/20/hello-tello-hacking-drones-with-go/ --> Video packets.

Can someone tell me how to do it?
`	
public void run(){
		System.out.println("thread is running");

		DatagramSocket serverSocket = null;
		try {
			serverSocket = new DatagramSocket(11111);
		} catch (SocketException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
        byte[] receiveData = new byte[1500];
		
		while(running == true) {
			DatagramPacket receivePacket = new DatagramPacket(receiveData, receiveData.length);
            try {
				serverSocket.receive(receivePacket);
			} catch (IOException e) {
				e.printStackTrace();
			}

            
            byte[] data = receivePacket.getData();
            
            System.out.println(data[0] + "     " + data[1]);
`

**Comment by trevrosen** [comment]
Hi there! There are several examples of using the Tello driver in our [examples directory](https://github.com/hybridgroup/gobot/tree/master/examples). Unfortunately we don't have the bandwidth to help you debug your Java code. :-(
