### ISSUE TITLE
APA102 LEDs driver: bad settings for brightness

### ISSUE THREAD

**Issue by air1bzz** [hybridgroup/gobot#664]
According to this [official documentation](https://cdn-shop.adafruit.com/datasheets/APA102.pdf), the LED Frame 32 bits starts with a 3 bits sequence (111) and 5 bits (Global) for brightness. The brightness cannot exceeds 31.
In the actual code the RGBA Red byte is set instead of Global making unexpected behaviour to the LED strip.

**Comment by air1bzz** [comment]
Above is my fix for this driver, i'm running it successfully on a project.

**Comment by deadprogram** [comment]
This code was release in v1.13.0 thank you! Now closing.
