### ISSUE TITLE
authentication between devices

### ISSUE THREAD

**Issue by nassimabedi** [hybridgroup/gobot#670]
I am beginner in IoT concepts.
I want to know when two device connect to each other how they authenticate. I see your first example "Button and LED" how they authenticate device to device or they use specific protocols like http or mqtt

Thank you for your help

**Comment by gen2thomas** [comment]
Hi @nassimabedi please can you exactly point to the example or just copy the code here, maybe I can give some answers.

Thanks Thomas

**Comment by gen2thomas** [comment]
I'm going to close this issue, because lack of further information. Please feel free to reopen, if this topic is still of interest.
