### ISSUE TITLE
When will gobot start using go modules

### ISSUE THREAD

**Issue by Ravenwater** [hybridgroup/gobot#681]

**Comment by andrewebdev** [comment]
Agree that this would be good to have. Would be good to have the ability to pin versions.

**Comment by deadprogram** [comment]
I would gladly accept a PR that switch to modules... please and thank you!

**Comment by deadprogram** [comment]
The modules code is now in the `dev`` branch.

**Comment by deadprogram** [comment]
This has now been released. Thanks everyone!
