### ISSUE TITLE
Beaglebone Green: GPIO already exported 

### ISSUE THREAD

**Issue by akhudek** [hybridgroup/gobot#685]
On the Beaglebone Green it turns out that GPIO pins start already exported. This causes Gobot to fail on the first run because it can't export the already exported pin. However, once Gobot shuts down, it unexports the pins and subsequently works on being restarted.

This is easy enough to work around by manually unexporting pins on device boot, but it would be nice if Gobot either more gracefully handled this situation or at least provided a way for the user to handle it.

**Comment by akhudek** [comment]
Actually, this is way more complicated. Turns out the beaglebone exports all the pins by default, and unexport doesn't work, it just errors out. But, if you try to export an already exported pin, *it unexports* it. Obviously unwanted behaviour. 

I have a patch for gobot that checks if the pin is already exported, but it's also more complicated than I thought due to some fixed needed to the gobot testing system. Not sure if it's worth doing a PR for this given it should probably be fixed in the beaglebone firmware.

**Comment by gen2thomas** [comment]
Hi @akhudek , do you know, if this is fixed now in BB green?

Thanks Thomas

**Comment by akhudek** [comment]
No clue, it's been years since I've used a beaglebone. Usually I just get pi's now.

**Comment by gen2thomas** [comment]
Thanks for the fast response, so I'm going to close this issue, because out of interest.
