### ISSUE TITLE
Raspi servo does not work as expected

### ISSUE THREAD

**Issue by erkexzcx** [hybridgroup/gobot#692]
**Description**

So servo should do a 180 degrees spin using this code:
```go
package main

import (
	"time"

	"gobot.io/x/gobot/drivers/gpio"
	"gobot.io/x/gobot/platforms/raspi"
)

func main() {
	adaptor := raspi.NewAdaptor()
	adaptor.Connect()

	servo := gpio.NewServoDriver(adaptor, "12")
	servo.Start()

	for i := uint8(0); i <= 180; i++ {
		servo.Move(i)
		time.Sleep(100 * time.Millisecond)
	}
}
```
To be exact, this below code should do a 180 degree servo spin:
```go
for i := uint8(0); i <= 180; i++ {
	servo.Move(i)
	time.Sleep(100 * time.Millisecond)
}
```
So according to documentation, `gpio.NewServoDriver` provides function `Move(uint8)` that expects numbers from 0 to 180 (represents a servo degree).

Unfortunately, my servo from AliExpress (says it's _Tower Pro Micro Servo 9G SG90_) does a full rotation on a range between 9 to 45, so range from 0 to 180 is useless and does not work correctly.

**Expected behavior**

Servo fully rotates to one side when I set `Move(0)` and should do 180degree spin when I set `Move(180)`.

**Actual behavior**

Servo doesn't do anything when I set `Move(0)` and doesn't do anything when I set `Move(180)`.

Instead, It fully rotates to one side when I set `Move(9)` and fully rotates to another side when I set `Move(45)`.

**Additional notes**

This is not an issue. It's just different servo. Tower Pro SG90 has pulse width of 500-2400 µs and it also struggles with pi-blaster as well (acceptable values are from 0.05 to 0.25 for 180 degree spin).

Is it possible to change some settings or set pulse width in gobot?

**Comment by erkexzcx** [comment]
Below code works as expected:
```go
package main

import (
	"time"

	"gobot.io/x/gobot/platforms/raspi"
)

func main() {
	adaptor := raspi.NewAdaptor()
	adaptor.Connect()

	for i := uint8(0); i <= 180; i++ {
		adaptor.ServoWrite("12", i)
		time.Sleep(40 * time.Millisecond)
	}
}
```

Why is everything so complicated? :(

**Comment by erkexzcx** [comment]
This is likelly my own issue. `Tower Pro SG90` has pulse width of `500-2400 µs`.

Is it possible to change it?

**Comment by garethschoeman** [comment]
hi @erkexzcx 

i know it has been super long since you posted this - but this helped me solve my issues. i can also only rotate 45 which ends up being 180 degrees. i am not sure if it is that the smaller servos only move in 4 degree increments or what.  if you managed to change it to move 180 degree angle let me know or if you kept it at every 1 = 4 degrees

**Comment by gen2thomas** [comment]
It looks like the "servo_driver.go" needs additional parameters, e.g. NewServoDriver(a, pin, minValue, maxValue) or, much better, we should add the options functionality like i2c drivers have (e.g. "WithLimits(min, max)").

I think this would be a nice enhancement.

**Comment by gen2thomas** [comment]
I'm going to close this issue as a duplicate, because it is now referenced by an issue which collect all the various problems with raspi and gpio.servo.
