### ISSUE TITLE
Can't run `Hello, World of Things` example on Arduino UNO

### ISSUE THREAD

**Issue by msclp** [hybridgroup/gobot#725]
What I have done:
1. Installed gort with homebrew
2. Ran `gort arduino install`
3. Ran `gort scan serial`
3. Ran `gort arduino upload firmata /dev/tty.usbmodem14201 -b uno`
4. Installed gobot with `go get -d -u gobot.io/x/gobot/...`
5. Copied _Hello, World of Things_ code example to `main.go` file (changed `"/dev/ttyACM0"` to `"/dev/tty.usbmodem14201"`
6. Ran `go run main.go`

Got error:
```
# github.com/go-ble/ble/darwin
../../../../go/src/github.com/go-ble/ble/darwin/device.go:67:12: cannot use d (type *Device) as type ble.DeviceOption in argument to opt:
	*Device does not implement ble.DeviceOption (missing SetConnectedHandler method)
```

**Comment by gen2thomas** [comment]
Either the given code relation is outdated or the issue relates to another repository. Therefore I going to close this issue. Feel free to reopen with more/new information.
