### ISSUE TITLE
Robot call backs for Start() and Halt()

### ISSUE THREAD

**Issue by kelah** [hybridgroup/gobot#727]
Hello,
   I think, it is good idea to add an option to include pre/post func() call back to execute any user defined action during initialisation and shutdown.

Best regards.

**Comment by gen2thomas** [comment]
Hi @kelah please can you provide some more background information for this idea. E.g. do you need a callback for the start of robots at all or for a specific robot? What do you want to achieve with this feature or what problem is to be solved?

Thanks Thomas
