### ISSUE TITLE
How to read the value of MCP3002 via  Raspberry Pi's SPI

### ISSUE THREAD

**Issue by u2yto** [hybridgroup/gobot#733]
I tried to read the temperature sensor value using MCP3002 via Raspberry Pi's SPI but it didn't work.

I ran the following code but got the error:
```golang
package main

import (
	"log"

	"gobot.io/x/gobot"
	"gobot.io/x/gobot/platforms/raspi"
	"gobot.io/x/gobot/drivers/spi"
)

func main() {
	r := raspi.NewAdaptor()
	d := spi.NewMCP3002Driver(r)

	gobot.NewRobot("robot",
		[]gobot.Connection{r},
		[]gobot.Device{d},
		func() {
			log.Println(d.AnalogRead("19"))
		},
	).Start()
}
```
The hardware layout:
 ![layout](https://user-images.githubusercontent.com/54768914/76193159-c022b200-6226-11ea-922f-79fa99c126ca.png)

**Comment by gen2thomas** [comment]
Hi @u2yto, if this is still relevant, please could you provide the output (the error). Otherwise we can't do or recommend anything without having the exact same hardware.

**Comment by gen2thomas** [comment]
I will going to close this issue, because a huge rework was done for SPI. Possibly the original failure is gone. Otherwise, please test with dev branch first and reopen or file a new one.
