### ISSUE TITLE
atmel mega328p microcontroller can emulate a HID?

### ISSUE THREAD

**Issue by PedroRiscado** [hybridgroup/gobot#740]
I have an arduino nano with a atmel mega328p microcontroller and idk if it can emulate a HID, to act like a keyboard and mouse. Someone can help me?

**Comment by shanduur** [comment]
Late to the party, although I have an answer.
Yes, ATMega328p can be used as HID device. Although to obtain the effect you want, you have to emulate / implement USB 1.1 - you can take a look at this project - [V-USB](https://github.com/obdev/v-usb). Also it won't work on the built in USB port - you have to add some circuitry by yourself.

**Comment by PedroRiscado** [comment]
Thanks man it will be very useful !!
