### ISSUE TITLE
go get -d -u gobot.io/x/gobot/... on windows failing

### ISSUE THREAD

**Issue by Sumanth-R-Y** [hybridgroup/gobot#741]
go version:
go version go1.14.1 windows/amd64

>go get -d -u gobot.io/x/gobot/...
**# cd xxxxxxxxx\go\src\go.bug.st\serial.v1; git pull --ff-only
fatal: not a git repository (or any of the parent directories): .git
package go.bug.st/serial.v1: exit status 128**

**Comment by Sumanth-R-Y** [comment]
Tried today and it is working.

**Comment by urban-wombat** [comment]
I'm seeing something similar:

$ go get -d -u gobot.io/x/gobot/...
# cd xxxxxxxxxx\golang\src\gobot.io\x\gobot; git pull --ff-only
fatal: not a git repository (or any parent up to mount point /cygdrive)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
package gobot.io/x/gobot/...: exit status 128

**Comment by pinnaclesystemsgroup** [comment]
Could SOMEONE PLEASE UPDATE THE SITE'S WEBPAGE AND MAKE IT THE INSTALL COMMAND CONSISTENT WITH THE GOLANG STANDARD THAT DEPRECATED THE "go get -d -u gobot.io/x/gobot/.." install command!!!!

**Comment by gen2thomas** [comment]
Hi @pinnaclesystemsgroup , thanks for pointing this out. PR's are greatly appreciated. So at least for the README.md this can be fixed by anyone.

**Comment by gen2thomas** [comment]
The CLI was removed and the documentation was updated. Currently there is a [known issue](https://github.com/hybridgroup/gobot/issues/920) with v2+ modules.
