### ISSUE TITLE
Can't install Gobot CLI

### ISSUE THREAD

**Issue by elie-g** [hybridgroup/gobot#744]
I get an error when I try to install the gobot CLI.
![error](https://i.imgur.com/NrDpsc9.png)

What am I doing wrong?

OS: Ubuntu 19.10
Go version: 1.14

**Comment by pseidemann** [comment]
you have `/gobot` twice in the path

**Comment by elie-g** [comment]
In fact, I did exactly what the [documentation](https://gobot.io/documentation/guides/cli/) says...
![doc](https://i.imgur.com/taFGCe3.png)

Anyway, it still doesn't work even with a single `/gobot` in the path.
![Not working](https://i.imgur.com/ke2Gl8t.png)

**Comment by pseidemann** [comment]
seems like a mistake. did you try https://github.com/hybridgroup/gobot/#getting-started?

**Comment by elie-g** [comment]
I don't have any problem with the library. I just can't install the CLI.

**Comment by pseidemann** [comment]
this should install the cli to the default go binaries directory as "gobot":
```go build -o "$(go env GOPATH)/bin/gobot" gobot.io/x/gobot/cli```
(derived from https://github.com/hybridgroup/gobot/blob/master/cli/README.md)

**Comment by elie-g** [comment]
It worked! Thanks! However, the documentation still need to be fixed.

**Comment by ramoncodes-collab** [comment]
It seems the documentation is not updated as @DrunkenPoney  mentions. Would be good if its updated

**Comment by deadprogram** [comment]
We'd gladly accept a PR that corrects the docs! :smile_cat:

**Comment by gen2thomas** [comment]
The CLI was removed and the documentation was updated. Currently there is a [known issue](https://github.com/hybridgroup/gobot/issues/920) with v2+ modules.
