### ISSUE TITLE
Servo doesn't work on raspberry pi

### ISSUE THREAD

**Issue by rochinworks** [hybridgroup/gobot#753]
I am having trouble getting a servo to move on a raspberry pi using the go1.13. I have never been able to get this to work. Is there something I'm missing? 
```
package main
import (
        "time"
	"fmt"

        "gobot.io/x/gobot"
        "gobot.io/x/gobot/drivers/gpio"
        "gobot.io/x/gobot/platforms/raspi"
)

func main() {
        r := raspi.NewAdaptor()
        servo := gpio.NewServoDriver(r, "24")

        work := func() {
		servo.Center()
		time.Sleep(1*time.Second)
		fmt.Println("moving servo to center")

		servo.Min()
		time.Sleep(1*time.Second)
		fmt.Println("moving servo to min")

		servo.Max()
		time.Sleep(1*time.Second)
		fmt.Println("moving servo to max")
        }

        robot := gobot.NewRobot("servoBot",
                []gobot.Connection{r},
                []gobot.Device{servo},
                work,
        )

        robot.Start()
}
```

**Comment by a1xon** [comment]
> https://raspberrypi.stackexchange.com/questions/70878/error-gpio-num-is-not-enabled-for-pi-blaster
> You have to 
> `sudo ./pi-blaster --gpio 13`


edit: sorry running into the same problems. the RPi Servo modul doesnt work with piblaster. I'm writing my own servo function now with https://github.com/richardghirst/PiBits/tree/master/ServoBlaster in the background. gobot seems like a dead project :\

**Comment by gen2thomas** [comment]
I'm going to close this issue as a duplicate, because it is now referenced by an issue which collect all the various problems with raspi and gpio.servo.
