### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by wlwatkins** [hybridgroup/gobot#754]
Hi, is this repo still maintained? I'm asking because some issues arise like the fact the robeaux.io does not exist and so on?

**Comment by deadprogram** [comment]
Yes Gobot is still maintained. Lots of users flying Tello drones etc.

Robeaux has very few (if any) active users but the repo is here: https://github.com/hybridgroup/robeaux

Hope that helps!

**Comment by wlwatkins** [comment]
for empty pages such as this one. Is it going to be updated? Can we contribute some code? 

https://gobot.io/documentation/drivers/servo/
