### ISSUE TITLE
Adafruit Driver wrongfully assumes both the Servo and DC Motors Hats are present

### ISSUE THREAD

**Issue by crazyquark** [hybridgroup/gobot#759]
This issue is at this line:
https://github.com/hybridgroup/gobot/blob/master/drivers/i2c/adafruit_driver.go#L152
If a Servo HAT is not installed, the driver Start method will return without trying to connect to the DC Motors HAT. 

This makes it impossible to use the Adafruit DC Motors HAT(https://www.adafruit.com/product/2348): 

I think if the connection to the Servo HAT fails(which is this product https://www.adafruit.com/product/2327) it should be just set to nil and then try to connect to the motors HAT. It shouldn't be mandatory to have both hats connected for this driver to work,

**Comment by gandaldf** [comment]
Can you please check if my proposed solution #783 works for you?

**Comment by gen2thomas** [comment]
@deadprogram it seems this fix is merged already, can we close the Issue?
