### ISSUE TITLE
Support for Jetson Nano platform

### ISSUE THREAD

**Issue by soerenbrockmann** [hybridgroup/gobot#772]
Do you plan to support Jetson Nano platform which runs on Ubuntu?
They mention that their platform (GPIO Pins) is equal to Raspberry PI. They only provide a Python :-(( GPIO Library.

**Comment by deadprogram** [comment]
Yes, absolutely planning on this.

**Comment by soerenbrockmann** [comment]
That would be amazing :-)

**Comment by soerenbrockmann** [comment]
I just tested this example here:


```
package main

import (
        "gobot.io/x/gobot/platforms/raspi"
)

func main() {
		r := raspi.NewAdaptor()
		fmt.Println(r)
}


```

I got this value returned:

&{0x400001c358 RaspberryPi-62F43657CD24D5FD  map[] map[] 0 [<nil> <nil>] 0 0 [<nil> <nil>] 0 0 10000000}

Is it a good sign? 

Is there a way to test connectivity without using a pin (I am afraid of breaking my board :-) )

**Comment by dlstjq7685** [comment]
@soerenbrockmann  
i just add feature jetson nano Adaptor.
check this branch.
https://github.com/hybridgroup/gobot/pull/799

**Comment by gen2thomas** [comment]
part of release v2.0.0
