### ISSUE TITLE
DirectPinDriver.AnalogWrite not programmed in

### ISSUE THREAD

**Issue by wlwatkins** [hybridgroup/gobot#773]
hi, 

in https://github.com/hybridgroup/gobot/blob/master/drivers/gpio/direct_pin_driver.go, there is in the comment an indication that analogWrite should be available, though it isi not in the code ???

**Comment by gen2thomas** [comment]
@willmendil it seems this is implemented by aio.go, so the comment is just wrong and should be removed.

**Comment by gen2thomas** [comment]
part of release v2.0.0
