### ISSUE TITLE
error run

### ISSUE THREAD

**Issue by fosfuchs** [hybridgroup/gobot#777]
i just run main.go

you are using a library that does not have newV2 and V2

ERROR:
```
# github.com/gobuffalo/uuid
../github.com/gobuffalo/uuid/generator.go:32:13: undefined: uuid.NewV2
../github.com/gobuffalo/uuid/uuid.go:41:7: undefined: uuid.V2
```

go version go1.15.6

**Comment by yurigorokhov** [comment]
bump! Affected by this as well.

**Comment by J0hn-B** [comment]
Any update on this?

**Comment by deadprogram** [comment]
We will have a new release soon with the fix. In the meantime, the `dev` branch has the updated version, if you would like to give that a try.
