### ISSUE TITLE
uuid needs replacing

### ISSUE THREAD

**Issue by georges-honore-figfi** [hybridgroup/gobot#780]
Hi,

Will there be further releases ?
If so, can you replace github.com/gobuffalo/uuid with github.com/gofrs/uuid
as it is deprecated

Cheers
Georges

**Comment by deadprogram** [comment]
Please see https://github.com/hybridgroup/gobot/pull/776 thanks!

**Comment by gen2thomas** [comment]
It is part of release 1.16.0 now
