### ISSUE TITLE
i2c helper_test.go ReadByteData() & ReadWordData() miss usage of "reg"

### ISSUE THREAD

**Issue by gen2thomas** [hybridgroup/gobot#789]
...therefore unit tests can not test:
* right register address was used
* count of writes (or written bytes) are correct

In general before reading any data, the register must be set by a write operation.

This can be performed by preceding:
```go
if err = t.WriteByte(reg); err != nil {
  return
}
```

**Comment by gen2thomas** [comment]
@deadprogram thanks for merging the PR to dev branch. What's your workflow for closing the issue?

**Comment by deadprogram** [comment]
Tagged with "next release" which is rather overdue. Will close on the actual release.

Thanks again @gen2thomas !
