### ISSUE TITLE
ssh1106 display driver (i2c)

### ISSUE THREAD

**Issue by maj-o** [hybridgroup/gobot#791]
Hello,

i have written a driver for the 128x64 1.3 inch display - and like to contribute the code

how can i do it - please, it's my very first contribution, a step by step list would be great

**Comment by deadprogram** [comment]
Hello @maj-o 

Please see https://github.com/hybridgroup/gobot/blob/release/CONTRIBUTING.md#contributing-to-gobot

Thank you!

**Comment by maj-o** [comment]
Hello Ron,

Thank You!

Regards Andreas

-----Original Message-----
