### ISSUE TITLE
Raspberry pi PICO

### ISSUE THREAD

**Issue by hasanAjsf** [hybridgroup/gobot#802]
Is gobot working with the new raspberry pi pico controller, different in the setup required from running raspberry pi with gobot, or every thing is the same as both having almost same processor?

https://www.raspberrypi.org/documentation/rp2040/getting-started/

**Comment by gen2thomas** [comment]
Hi @hasanAjsf , it seems there is no information available at this point. In the meantime, do you have made some experiences with the PICO, which you can share with us?

**Comment by jackjameshoward** [comment]
has there been any more consideration given for support to this device? 
I don't know how similar gobot is to tinygo, but there is support for the pico over there.   
https://tinygo.org/docs/reference/microcontrollers/pico/

**Comment by gen2thomas** [comment]
As far as I can tell Microcontrollers are supported by [firmata](https://github.com/hybridgroup/gobot/tree/release/platforms/firmata) protocol in gobot. So, if the firmata firmware supports the hardware it should work, but I have no experience with that. The "normal [Raspi](https://github.com/hybridgroup/gobot/tree/release/platforms/raspi)", which is supported by gobot, is a computer with installed Linux OS.

**Comment by gen2thomas** [comment]
I'm going to close this issue, because there are 2 alternative ways available to use the PICO microcontroller. @hasanAjsf feel free to reopen the issue with providing more information why you need/want to use gobot over tinygo.
