### ISSUE TITLE
I2C driver typo: change HMC8553L to HMC5883L

### ISSUE THREAD

**Issue by bryanjhv** [hybridgroup/gobot#805]
Thanks @yurigorokhov for #781 but...

It looks like there's a typo regarding driver name.

Should be <code>HMC**5883**L</code> instead of <code>HMC**8553**L</code>.

**Comment by gen2thomas** [comment]
I ordered such an device and also stumbled about this mismatch. I will test it with my Tinkerboard and when it works I will provide a bugfix.

**Comment by gen2thomas** [comment]
part of release v2.0.0
