### ISSUE TITLE
Please remove  the import for github.com/gobuffalo/uuid and import github.com/gofrs/uuid directly

### ISSUE THREAD

**Issue by champ-isaac** [hybridgroup/gobot#807]
Since github.com/gobuffalo/uuid has been deprecated and it also recommends to use github.com/gofrs/uuid directly.
At mean time, gofrs/uuid had removed NewV2, it caused the error of undefined: uuid.NewV2 in go buffalo/uuid.

**Comment by gen2thomas** [comment]
@champ-isaac it is there since 1.16.0, see https://github.com/hybridgroup/gobot/blob/d8081f912d324f570c6e3fa74aba7c203e53bb27/go.mod#L11
