### ISSUE TITLE
Is the project abandon?

### ISSUE THREAD

**Issue by arthuravila26** [hybridgroup/gobot#808]
I'm thinking in start to practice Go using my IoT ideas but I'm kind worried to use this framework and it is abandon as the last merge in the code was in 2020. If it is, does some know another framework that is good to use Go in IoT projects?

**Comment by gen2thomas** [comment]
Hi @arthuravila26 , no it is not abandon, but a little bit slow ;o}. Help to fix some bugs or make some new device drivers is greatly appreciated.
