### ISSUE TITLE
write /dev/i2c-1: remote I/O error on Raspberry Pi Zero 2 W and Adafruit Motorhat

### ISSUE THREAD

**Issue by kevensen** [hybridgroup/gobot#809]
I am trying to run https://github.com/hybridgroup/gobot/blob/release/examples/raspi_adafruit_stepper.go. I am receiving the following error:

```
2022/02/22 18:21:36 Initializing connections...
2022/02/22 18:21:36 Initializing connection RaspberryPi-6579FA62 ...
2022/02/22 18:21:36 Initializing devices...
2022/02/22 18:21:36 Initializing device AdafruitMotorHat-323C1392 ...
2022/02/22 18:21:36 Robot adaFruitBot initialized.
2022/02/22 18:21:36 Starting Robot adaFruitBot ...
2022/02/22 18:21:36 Starting connections...
2022/02/22 18:21:36 Starting connection RaspberryPi-6579FA62...
2022/02/22 18:21:36 Starting devices...
2022/02/22 18:21:36 Starting device AdafruitMotorHat-323C1392...
2022/02/22 18:21:36 1 error occurred:
	* write /dev/i2c-1: remote I/O error
```
When I run `sudo i2cdetect -y 1` I get the following
```
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: 60 -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: 70 -- -- -- -- -- -- -- 
```

My wiring is correct and verified by a Python example.

This seems similar to https://github.com/hybridgroup/gobot/issues/782.  Any help is appreciated.

**Comment by gen2thomas** [comment]
Hi @kevensen , I have reworked the driver by splitting it to one driver for each HAT, which is more gobot style and also gives the possibility to reuse the code from i2c device PCA9685. My test was done with PCA9685 based board, but not the adafruit HAT, but should working also for the HAT. This is still released with [2.2.0](https://github.com/hybridgroup/gobot/releases/tag/v2.2.0). So I'm going to close this issue for now. Feel free to reopen if it is not working for you.
