### ISSUE TITLE
Does this Lib. Still Work w/ the BeagleBone Black?

### ISSUE THREAD

**Issue by silver2row** [hybridgroup/gobot#816]
Hello,

I have not tried this out yet. I plan on trying it out to handle some LED to start via the BeagleBone Black and RelayCape.

Here: https://github.com/hybridgroup/gobot/tree/master/platforms/beaglebone

Is this still current or would I need to update in my cloned repo. a way to handle this lib?

Seth

**Comment by gen2thomas** [comment]
Hi @silver2row have you been able to check this out yet ? Could you test the dev branch for your requirements?

**Comment by stevstrong** [comment]
The newest package does have a problem at install.
I followed this page:
https://gobot.io/documentation/platforms/beaglebone/
Having Go already installed, I started to install gobot with:
`go get -d -u gobot.io/x/gobot/...`
And after downloading a lot of packages, it throws these lines:
```
gobot.io/x/gobot/drivers/spi imports
        periph.io/x/periph/conn/physic: cannot find module providing package periph.io/x/periph/conn/physic
gobot.io/x/gobot/drivers/spi imports
        periph.io/x/periph/conn/spi: cannot find module providing package periph.io/x/periph/conn/spi
gobot.io/x/gobot/drivers/spi imports
        periph.io/x/periph/host/sysfs: cannot find module providing package periph.io/x/periph/host/sysfs
```
So I assume something is wrong there.
Can someone help to fix this?

**Comment by gen2thomas** [comment]
Hi @stevstrong , the documentation at [this page](https://gobot.io/documentation/platforms/beaglebone/) is outdated. We only support the v2 of gobot. Please have a look at this example instead: https://github.com/hybridgroup/gobot/blob/release/examples/beaglebone_blink.go.

Also the [getting started guide](https://github.com/hybridgroup/gobot/blob/release/README.md#getting-started) could be helpful.

Good luck, Thomas

**Comment by stevstrong** [comment]
So you say that there is no need to install it as specified on the page I linked?
Just checkout from git and use it?

**Comment by gen2thomas** [comment]
This depends on your start point. If you already have a go program or project for your platform a `go mod tidy` should be sufficient (after you have changed the old imports to "gobot/v2"). Otherwise, please read the guide and try it step by step.

**Comment by gen2thomas** [comment]
Hi @stevstrong , do you have any progress on that? Can we close this issue?

Thanks Thomas

**Comment by stevstrong** [comment]
Hi,
 I abandoned this project, so feel free to close this if you think that it is not relevant anymore.

**Comment by gen2thomas** [comment]
Hi @stevstrong , thanks for the fast response, so I will close this issue.
