### ISSUE TITLE
i2c/smBus ReadBlockData() not implemented, all "Read*Data()" of digispark and firmata are wrong implemented

### ISSUE THREAD

**Issue by gen2thomas** [hybridgroup/gobot#832]
According to the [Kernel specification](https://docs.kernel.org/i2c/smbus-protocol.html#smbus-block-read) it should be possible to implement this function. The opposite ["WriteBlockData()" is still implemented](https://github.com/hybridgroup/gobot/blob/d8081f912d324f570c6e3fa74aba7c203e53bb27/drivers/i2c/i2c.go#L44).

Following drivers could be simplified:
* [th02_driver.go](https://github.com/hybridgroup/gobot/blob/d8081f912d324f570c6e3fa74aba7c203e53bb27/drivers/i2c/th02_driver.go#L234)
* [mpu6050_driver.go](https://github.com/hybridgroup/gobot/blob/d8081f912d324f570c6e3fa74aba7c203e53bb27/drivers/i2c/mpu6050_driver.go#L100)
* [mpl115a2_driver.go](https://github.com/hybridgroup/gobot/blob/d8081f912d324f570c6e3fa74aba7c203e53bb27/drivers/i2c/mpl115a2_driver.go#L120) and for [getData()](https://github.com/hybridgroup/gobot/blob/d8081f912d324f570c6e3fa74aba7c203e53bb27/drivers/i2c/mpl115a2_driver.go#L156)
* [l3gd20h_driver.go](https://github.com/hybridgroup/gobot/blob/d8081f912d324f570c6e3fa74aba7c203e53bb27/drivers/i2c/l3gd20h_driver.go#L115)
* HMC5883L in ReadRawData()
* [ccs811_driver.go](https://github.com/hybridgroup/gobot/blob/d8081f912d324f570c6e3fa74aba7c203e53bb27/drivers/i2c/ccs811_driver.go#L339), an implementation of read block data, also used in all 3 bmpx80 and bme280 drivers
* [adxl345_driver.go](https://github.com/hybridgroup/gobot/blob/d8081f912d324f570c6e3fa74aba7c203e53bb27/drivers/i2c/adxl345_driver.go#L222)

Some notes for support of block-read: 
* "i2cdetect -F 0" show the state
* Raspi Kernel version 4.9.35 [related bug](https://github.com/raspberrypi/firmware/issues/828)
* Tinkerboard "Tinker_Board-Debian-Buster-v3.0.11-20211026" no support
* digispark (using littlewire) support it since #833 
* the implemented fallback is used automatically, if not supported

**Comment by deadprogram** [comment]
That sounds like a great idea!

**Comment by gen2thomas** [comment]
While rework of PCA9501 i2c driver (see #786 ), I found that all implementations of Read*Data() in digispark (and also in firmata) are wrong implemented, regarding to the [Kernel specification](https://docs.kernel.org/i2c/smbus-protocol.htm) and the implementation of sys-fs driver.

[Read Byte](https://docs.kernel.org/i2c/smbus-protocol.html#smbus-read-byte) (Comm==Register)
S Addr Wr [A] Comm [A] **Sr** Addr Rd [A] [Data] NA P
We have implemented in "ReadByteData()":
S Addr Wr [A] Comm [A] **P S** Addr Rd [A] [Data] NA P

[Read Word](https://docs.kernel.org/i2c/smbus-protocol.html#smbus-read-word)
S Addr Wr [A] Comm [A] **Sr** Addr Rd [A] [DataLow] A [DataHigh] NA P
Implemented in "ReadWordData()":
S Addr Wr [A] Data [A] **P S** Addr Rd [A] [DataLow] A [DataHigh] NA P

In general most chips support both sequences, but unfortunately not all, e.g. PCA9501, which only support the "Read Byte".

At least the littlewire interface, used for digispark, support the skip of stop condition ("P"), so the change is generally no problem.

**Comment by gen2thomas** [comment]
Hi @deadprogram , because I'm not familiar with firmata in general and with client "writes an arbitrary Sysex command to the microcontroller" in special, I'm just marked the wrong implemented commands with an TODO and will create a new issue for this special behavior.

**Comment by gen2thomas** [comment]
part of release v2.0.0
