### ISSUE TITLE
CI/CD environment outdated

### ISSUE THREAD

**Issue by gen2thomas** [hybridgroup/gobot#849]
* deprecated  (circleci), see https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034
* golang [1.15 is used](https://github.com/hybridgroup/gobot/blob/f141a2bc7a562f500ced5ab679bede9816fa01f1/.circleci/config.yml#L6), which cause CI build errors for new functions of golang 1.16 (e.g. os.ReadDir), see https://app.circleci.com/pipelines/github/hybridgroup/gobot/40/workflows/ef2f4957-0873-4dd8-8784-dfe5c9348e12/jobs/40

**Comment by deadprogram** [comment]
Fixed!

**Comment by gen2thomas** [comment]
Thanks for fast merging.

Mhm, unfortunately the change from /go to $HOME/go in new cimg seems to make some problems, see
https://app.circleci.com/pipelines/github/hybridgroup/gobot/41/workflows/dfaa8bbf-48ed-4b6e-b91b-bbceedd52bba/jobs/41?invite=true#step-101-73

Is there a reason why we see this problems only on "dev"? - Yes, because we run the circleci not on feature branches, only the "appveyor" build. 

Is this done by intention?

The "appveyor" build and test is done on a windows environment. Some tests can most likely not run on this platform:
* the sysfs-tests (generic access to linux gpio)
* all adaptor tests which depends on sysfs (means all, except firmata)

**Comment by gen2thomas** [comment]
After merging the last fix, tests will be start. But following tests now fail:
* "utils_test.go:38: Every was not called"
* "utils_test.go:44: Every should have stopped"

Because this tests running before without any problems, it seems to be flaky.

Also this test seems to be flaky:
*  "client_test.go:466: SysexResponse was not published"

**Comment by deadprogram** [comment]
Yes, they appear to be very sensitive to race conditions/timing.

**Comment by gen2thomas** [comment]
still unstable:
* [core](https://app.circleci.com/pipelines/github/hybridgroup/gobot/68/workflows/9f80bfb8-d832-4e19-8c26-262ce31b116c/jobs/75?invite=true#step-103-70)

* [platforms](https://app.circleci.com/pipelines/github/gen2thomas/gobot/8/workflows/30de7e0f-203f-4529-a5ad-87fd10c02ee1/jobs/16?invite=true#step-103-400)

**Comment by gen2thomas** [comment]
part of release v2.0.0
