### ISSUE TITLE
go.mod and some dependencies outdated

### ISSUE THREAD

**Issue by gen2thomas** [hybridgroup/gobot#860]
currently go 1.13 is used in go.mod
and also some used dependencies can switch to a newer version

this guides are very useful: 
* https://go.dev/doc/modules/managing-dependencies
* https://golang.cafe/blog/how-to-upgrade-golang-dependencies.html

long story short:
go list -m -u all
go get -t -u ./...
go mod tidy
make test (possibly take some time to compile sdl2 package initially)

**Comment by deadprogram** [comment]
See https://github.com/hybridgroup/gobot/pull/856 where I have updated a bunch f these already.

**Comment by gen2thomas** [comment]
Hi @deadprogram I have seen that you have already started upgrading with #856 .

Is the go version 1.16 used intentionally?
Debian bullseye uses 1.15, backports 1.19 and bookworm will most likely use 1.19.

**Comment by deadprogram** [comment]
Actually I meant to pick 1.17 with intention like Go to support current version minus 2.

**Comment by gen2thomas** [comment]
Ok, so we should align it with used version in circleci? Currently I have chosen "cimg/go:1.19".

**Comment by gen2thomas** [comment]
part of release v2.0.0
