### ISSUE TITLE
Sphero Collision Detection Sensitivity

### ISSUE THREAD

**Issue by nathany** [hybridgroup/gobot#90]
Collision events didn't trigger consistently from a Sphero 1.0. We tweaked the settings at https://github.com/hybridgroup/gobot/blob/master/platforms/sphero/sphero_driver.go#L181 to make it more sensitive.

Maybe it would be worth exposing those settings as an API? (with reasonable defaults, of course). We are hoping to detect collisions with other Spheros while filtering out collisions with foam walls -- that may result in settings different than what other people would use.

Reference: [collision detection docs](http://orbotixinc.github.io/Sphero-Docs/docs/collision-detection/index.html) and the packet under [Configure Collision Detection – 12h](http://orbotixinc.github.io/Sphero-Docs/docs/sphero-api/bootloader-and-sphero.html).

**Comment by deadprogram** [comment]
Hi, @nathany 

Did you ever look over the added functionality for Sphero, and see if it addressed your needs?

If so, can you please close this issue? Thanks.

**Comment by nathany** [comment]
I don't recall. It's been a while since i've used my Sphero for anything. Happy to close the issue though.
