### ISSUE TITLE
release request for gobot 2.0.0

### ISSUE THREAD

**Issue by gen2thomas** [hybridgroup/gobot#900]
Hi @deadprogram , a software is never perfect, but we get fixed a lot in the past month and furthermore, added some new features. What do you think about a gobot release? Can you do that?

Also the home page https://gobot.io/ was last updated some years ago and miss some already included drivers. Who is able to update this?

Thanks for your support, Thomas

**Comment by brainbaking** [comment]
Hi, I'm contemplating on contributing to Gobot to add compatibility with a non-raspberry pi SBC, but looking at current pull requests and the latest checkin in the main branch, I wonder: is Gobot still actively being developed?

**Comment by gen2thomas** [comment]
Hi, contributing is always welcome. The default branch is the "release" branch with latest commit in May 2022. Development effort is done on dev-branch, see [CONTRIBUTING.md](https://github.com/hybridgroup/gobot/blob/release/CONTRIBUTING.md).

**Comment by gen2thomas** [comment]
Hi @deadprogram , maybe you are too busy to do the merge at the moment, maybe you want wait some time for any reason? Please let me know if I should do this and teach me how.

**Comment by gen2thomas** [comment]
To answer my own question - the home page seems to be based on the resources of this repo: https://github.com/hybridgroup/gobot-site

**Comment by deadprogram** [comment]
@gen2thomas the site is based on very old static site generator. Trying to get it working again to update is a seemingly big task. The best would be to migrate to Hugo?

**Comment by gen2thomas** [comment]
Hi @deadprogram , I'm not familiar with Middleman or Hugo but RoR (long time ago), lets discuss this topic in the already existing https://github.com/hybridgroup/gobot-site/issues/61.

What do you think about a new release of gobot? Can you teach me about the steps to do?

**Comment by gen2thomas** [comment]
I will do it in this way:
* [x] prepare draft PR for code dev --> release
* [x] prepare draft PR for CHANGELOG.md & version feature-branch --> dev
* [x] merge code to release
* [x] merge changelog to dev, afterwards to release
* [x] create a new release with description from added changelog

**Comment by gen2thomas** [comment]
part of release v2.0.0
