### ISSUE TITLE
CLI generate templates outdated

### ISSUE THREAD

**Issue by gen2thomas** [hybridgroup/gobot#918]
The [template content](https://github.com/hybridgroup/gobot/commits/release/cli) is not updated since 2018. Maintaining templates can be a big task and, if this is not done regularly, new code is also outdated and the start is more frustrating for new developers and reviewers. IMO new developers should use one of the latest adaptors/drivers/platforms as "blueprint".

So my suggestion is to remove this folder completely to reduce maintaining effort.

@deadprogram what do you think?

**Comment by deadprogram** [comment]
Agree, let's remove.

**Comment by gen2thomas** [comment]
* [x] remove cli folder
* [x] remove version.go
* [x] remove snapcraft.yml
* [x] update documentation
* [x] adjust documentation regarding to "go get" vs "go install" (go get now reports an error when used outside a module, since there is no go.mod file to update, with go 1.18)
* [x] close/comment related issues (e.g. #741 , #744 , #377)
