### ISSUE TITLE
Time synchronization for multi-Sphero collision detection

### ISSUE THREAD

**Issue by nathany** [hybridgroup/gobot#94]
In order for the timestamp values in #93 to be useful, there are two Core APIs that need to be implemented:

Assign Time Value – 50h
Poll Packet Times – 51h

http://orbotixinc.github.io/Sphero-Docs/docs/sphero-api/the-core.html

If possible, I'd like this to be completely internal to the SpheroDriver, but an exported API may be helpful when communicating Sphero timestamps to a network server. Still need to look into it more.

A bit more on detecting multi-Sphero collisions:
http://stackoverflow.com/questions/15234516/is-there-a-more-accurate-way-to-detect-ball-to-ball-collisions-with-sphero-api

**Comment by deadprogram** [comment]
I am closing this issue due to age. Please reopen if needed, and thanks!
