### ISSUE TITLE
branch protection

### ISSUE THREAD

**Issue by gen2thomas** [hybridgroup/gobot#945]
Hi @deadprogram , I had removed the dev branch accidentally after a merge 2 weeks ago and restored it immediately. Nevertheless all PR's where closed on this action. I'm aware on this some hours/days later and had to reopen all of it.

It seems there is a possibility to protect branches against this action (delete). So please, can you make this for "dev" and "release" branch?

Thanks Thomas

**Comment by deadprogram** [comment]
Done. Thanks @gen2thomas
