### ISSUE TITLE
cannot find modules on install

### ISSUE THREAD

**Issue by jney** [hybridgroup/gobot#968]
Install `go get -d -u gobot.io/x/gobot/...` terminate with the following errors

```
gobot.io/x/gobot/drivers/spi imports
	periph.io/x/periph/conn/physic: cannot find module providing package periph.io/x/periph/conn/physic
gobot.io/x/gobot/drivers/spi imports
	periph.io/x/periph/conn/spi: cannot find module providing package periph.io/x/periph/conn/spi
gobot.io/x/gobot/drivers/spi imports
	periph.io/x/periph/host/sysfs: cannot find module providing package periph.io/x/periph/host/sysfs
```

**Comment by gen2thomas** [comment]
Hi @jney , please use "gobot/v2/" or after creating your application use "go mod tidy" instead.

**Comment by gen2thomas** [comment]
A new documentation is released now, so I will close this issue. Feel free to reopen if we should do something more.

**Comment by tlindsay** [comment]
@gen2thomas The [GoBot Getting Started](https://gobot.io/documentation/getting-started/) guide still lists this as the first step:
```
$ go get -d -u gobot.io/x/gobot/...
```

**Comment by gen2thomas** [comment]
@tlindsay yes, this is outdated in many places, but there is no time to [fix it](https://github.com/hybridgroup/gobot-site/issues/61).
