### ISSUE TITLE
joystick: switch to use github.com/0xcafed00d/joystick package

### ISSUE THREAD

**Issue by deadprogram** [hybridgroup/gobot#986]
I propose that we switch to use the https://github.com/0xcafed00d/joystick package for joystick.

It works on Linux, macOS, and Windows, and does not require go-sdl which avoids a lot of CGo and other toolchain complexity.

**Comment by deadprogram** [comment]
@gen2thomas any opinions on this?

**Comment by gen2thomas** [comment]
Hi @deadprogram , I do not use joysticks at the moment, but in addition to your points:
* the automated tests are problematic due to SDL
* the first build of project takes longer due to SDL

...so an improvement is greatly appreciated.

**Comment by gen2thomas** [comment]
available since v2.2.0
